"""3 comprehensive lead magnet guide articles for SharpPages."""


def get_lead_magnet_articles(PRICING):
    """Return 3 lead magnet blog article dicts."""
    return [
        {
            "slug": "website-speed-checklist-47-items",
            "title": "The Complete Website Speed Checklist: 47 Things to Check",
            "description": "A 47-item checklist covering images, CSS, JavaScript, fonts, server configuration, third-party scripts, and CMS-specific fixes to maximize your PageSpeed score.",
            "h1": "The Complete Website Speed Checklist: 47 Things to Check",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "Images (Items 1-8)",
                    "content": '<ol>\n<li><strong>Convert to WebP or AVIF.</strong> WebP is 25-35% smaller than JPEG. AVIF is 30-50% smaller. All modern browsers support both. This is the single highest-impact change for most sites.</li>\n<li><strong>Add responsive srcset.</strong> Serve 400px images to phones, 800px to tablets, 1200px to desktops. Mobile users should not download desktop-sized images.</li>\n<li><strong>Lazy-load below-the-fold images.</strong> Add <code>loading="lazy"</code> to every image below the initial viewport. Do NOT lazy-load the hero image.</li>\n<li><strong>Set explicit width and height.</strong> Every <code>&lt;img&gt;</code> tag needs width and height attributes. Without them, the browser cannot reserve space, causing layout shift (CLS).</li>\n<li><strong>Compress to target sizes.</strong> Hero images under 100KB. Content images under 50KB. Thumbnails under 20KB. Any image over 200KB needs attention.</li>\n<li><strong>Use fetchpriority="high" on the hero image.</strong> This tells the browser to prioritize downloading the LCP element before other resources.</li>\n<li><strong>Remove EXIF data.</strong> Camera metadata adds 10-50KB per image. Strip it during compression.</li>\n<li><strong>Serve images from a CDN.</strong> Images hosted on a CDN load from the nearest edge server. This reduces latency by 50-200ms per image on first load.</li>\n</ol>',
                },
                {
                    "heading": "CSS (Items 9-15)",
                    "content": '<ol start="9">\n<li><strong>Inline critical CSS.</strong> CSS needed to render the visible viewport should be in the <code>&lt;head&gt;</code>, not in an external file. This eliminates a render-blocking request.</li>\n<li><strong>Remove unused CSS.</strong> Most sites load CSS for components not on the current page. Tools like PurgeCSS can strip unused rules. Our static sites ship 25-40KB of CSS because every rule is intentional.</li>\n<li><strong>Minify CSS.</strong> Remove whitespace, comments, and redundant syntax. Saves 15-30% file size. Use cssnano or Lightning CSS.</li>\n<li><strong>Avoid CSS @import.</strong> @import creates sequential loading. Use <code>&lt;link&gt;</code> tags instead so the browser downloads CSS files in parallel.</li>\n<li><strong>Use CSS instead of JavaScript for interactions.</strong> Smooth scroll, hover effects, accordions (<code>&lt;details&gt;</code>), and simple animations can all be CSS-only.</li>\n<li><strong>Reduce specificity and nesting.</strong> Deeply nested selectors slow style recalculation. Keep selectors flat and specific.</li>\n<li><strong>Consolidate to one CSS file.</strong> Multiple CSS files mean multiple HTTP requests. Combine into one minified file under 50KB.</li>\n</ol>',
                },
                {
                    "heading": "JavaScript (Items 16-23)",
                    "content": '<ol start="16">\n<li><strong>Defer all non-critical JS.</strong> Add <code>defer</code> to script tags. This downloads in parallel but executes after HTML parsing.</li>\n<li><strong>Remove unused JavaScript libraries.</strong> If you loaded jQuery for one animation, replace it with 5 lines of vanilla JS and save 90KB.</li>\n<li><strong>Audit every script.</strong> For each script: is it still used? Can it be replaced with CSS? Does it need to load on every page?</li>\n<li><strong>Load third-party scripts after DOMContentLoaded.</strong> Analytics, chat widgets, and tracking pixels do not need to block page rendering.</li>\n<li><strong>Bundle and minify.</strong> Combine JavaScript files and minify with Terser or esbuild. Reduces requests and file size.</li>\n<li><strong>Remove console.log and dev-only code.</strong> Development artifacts add bytes that production visitors download.</li>\n<li><strong>Limit Total Blocking Time.</strong> Keep TBT under 200ms. If any single script takes more than 50ms to execute, split it or defer it.</li>\n<li><strong>Avoid document.write.</strong> It forces synchronous parsing and blocks rendering.</li>\n</ol>',
                },
                {
                    "heading": "Fonts (Items 24-28)",
                    "content": '<ol start="24">\n<li><strong>Use font-display: swap.</strong> Shows text immediately in a fallback font, then swaps when the custom font loads. Prevents invisible text.</li>\n<li><strong>Self-host fonts.</strong> Loading from Google Fonts adds 2 extra round trips (DNS + CSS). Self-hosting is one round trip.</li>\n<li><strong>Preload the primary font.</strong> <code>&lt;link rel="preload" href="/fonts/main.woff2" as="font" type="font/woff2" crossorigin&gt;</code></li>\n<li><strong>Limit font weights.</strong> Each weight is a separate file. Two to three weights (400, 600, 700) cover most designs. Do not load 6 weights.</li>\n<li><strong>Use variable fonts.</strong> One file contains all weights. Often smaller total size than loading 3-4 individual weight files.</li>\n</ol>',
                },
                {
                    "heading": "Server and Hosting (Items 29-35)",
                    "content": '<ol start="29">\n<li><strong>Target TTFB under 200ms.</strong> If your server takes 800ms to respond, nothing else can start. Move to managed hosting or static files on a CDN.</li>\n<li><strong>Enable GZIP or Brotli compression.</strong> Reduces text-based file transfers by 60-80%. Most modern hosts enable this by default.</li>\n<li><strong>Set Cache-Control headers.</strong> Static assets (CSS, JS, images, fonts) should have <code>max-age=31536000</code>. Use versioned filenames for cache busting.</li>\n<li><strong>Use a CDN.</strong> Cloudflare (free tier) or another CDN ensures assets are served from the nearest edge server worldwide.</li>\n<li><strong>Enable HTTP/2 or HTTP/3.</strong> Multiplexes requests over a single connection. Most modern hosts support this.</li>\n<li><strong>Use HTTPS.</strong> Required for HTTP/2, improves security, and is a minor ranking signal. Free via Let\'s Encrypt.</li>\n<li><strong>Consider static hosting.</strong> GitHub Pages, Cloudflare Pages, and Netlify serve static files from a global CDN for $0. TTFB: 10-30ms.</li>\n</ol>',
                },
                {
                    "heading": "Third-Party Scripts (Items 36-41)",
                    "content": '<ol start="36">\n<li><strong>Audit all third-party scripts.</strong> Open DevTools Network tab, filter by third-party. Count requests and total size. Common offender: chat widgets at 200-400KB.</li>\n<li><strong>Remove unused tracking.</strong> If nobody checks the Hotjar dashboard, remove the script. Every removed script improves speed with zero effort.</li>\n<li><strong>Replace chat widgets with a contact link.</strong> If less than 1% of visitors use chat, save 200-400KB on every page load for the 99% who do not.</li>\n<li><strong>Use Google Tag Manager sparingly.</strong> GTM makes it easy to add scripts. That ease leads to bloat. Audit GTM tags quarterly.</li>\n<li><strong>Delay non-essential scripts until interaction.</strong> Load analytics on first scroll. Load chat on first click. Keeps initial load clean.</li>\n<li><strong>Consolidate analytics.</strong> GA4 + Facebook Pixel + Hotjar + HubSpot = 4 tracking scripts. Do you need all of them? Each one costs 30-80KB.</li>\n</ol>',
                },
                {
                    "heading": "CMS-Specific (Items 42-47)",
                    "content": f'<ol start="42">\n<li><strong>WordPress: Reduce plugins to under 10.</strong> Each plugin adds global JS/CSS. 20 plugins = 800KB+ of overhead. Audit and remove ruthlessly.</li>\n<li><strong>WordPress: Replace page builders with a lightweight theme.</strong> Elementor adds 300KB+ to every page. GeneratePress or Astra add under 30KB.</li>\n<li><strong>WordPress: Enable server-side caching.</strong> WP Rocket or LiteSpeed Cache. Eliminates PHP processing on repeat visits.</li>\n<li><strong>Webflow: Minimize interactions.</strong> Each interaction adds JS payload. Sites with 10+ interactions score 8-15 points lower.</li>\n<li><strong>Webflow: Optimize images manually.</strong> Webflow does not enforce image optimization. Compress before uploading.</li>\n<li><strong>Consider rebuilding on static HTML.</strong> If you have exhausted the above items and still cannot break 85, the platform is the bottleneck. Static HTML scores 90-98 by default. Migration starts at ${PRICING["redesign_wp_sq_wix"]["low"]:,}. <a href="/audit/">Audit your site</a> to see the gap.</li>\n</ol>\n<p>Read our <a href="/blog/page-speed-optimization-guide/">complete page speed optimization guide</a> for detailed explanations of each technique.</p>',
                },
            ],
            "faqs": [
                {"question": "Which items should I fix first?", "answer": "Images (items 1-8) and JavaScript (items 16-23) have the highest impact. Image optimization alone can improve scores by 15-30 points. Deferring JavaScript reduces Total Blocking Time immediately."},
                {"question": "How long does it take to work through this checklist?", "answer": "Basic items (image compression, defer scripts, caching headers) take 1-2 days. Advanced items (critical CSS, font optimization, third-party script management) take 3-5 days. A full audit and fix cycle typically takes 1-2 weeks."},
                {"question": "What if I fix everything and still score below 85?", "answer": f"The platform is the bottleneck. WordPress, Webflow, and Squarespace have architectural ceilings. Rebuilding on static HTML is the only way to consistently score 90+. Migration starts at ${PRICING['redesign_wp_sq_wix']['low']:,}."},
                {"question": "Do I need to implement all 47 items?", "answer": "No. Focus on the high-impact items first (images, JavaScript, caching). Most sites can gain 20-30 points by fixing items 1-8 and 16-23. The remaining items provide incremental improvements."},
            ],
        },
        {
            "slug": "core-web-vitals-quick-fix-guide",
            "title": "Core Web Vitals Quick-Fix Guide: Pass All Three in One Weekend",
            "description": "A practical weekend guide to fixing LCP, CLS, and INP. Friday evening audit, Saturday image and layout fixes, Sunday JavaScript and verification.",
            "h1": "Core Web Vitals Quick-Fix Guide: Pass All Three in One Weekend",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "The Weekend Plan",
                    "content": '<p>Google\'s Core Web Vitals measure three things: how fast the largest element appears (LCP), how stable the layout is (CLS), and how responsive the page is to interaction (INP). Passing all three means: LCP under 2.5 seconds, CLS under 0.1, INP under 200ms.</p>\n<p>Most sites fail one or two of these on mobile. The fixes are usually straightforward but require focused attention. This guide gives you a weekend plan: Friday evening for diagnosis, Saturday for LCP and CLS fixes, Sunday for INP and verification.</p>\n<p>You will need: access to your site files or CMS, <a href="https://pagespeed.web.dev/" target="_blank" rel="noopener noreferrer">PageSpeed Insights</a>, and Chrome DevTools. Read our <a href="/blog/core-web-vitals-explained-lcp-cls-tbt/">Core Web Vitals explainer</a> if you need background on what each metric measures.</p>',
                },
                {
                    "heading": "Friday Evening: Audit and Baseline",
                    "content": '<p><strong>Step 1: Record your baselines.</strong> Run your top 5 pages through PageSpeed Insights on mobile. Record LCP, CLS, TBT (proxy for INP), and the overall Performance score. Run each page 3 times and average the results.</p>\n<p><strong>Step 2: Identify the LCP element.</strong> In PageSpeed Insights, expand the "Largest Contentful Paint element" diagnostic. It tells you exactly which element is your LCP: usually a hero image, a large heading, or a background image.</p>\n<p><strong>Step 3: Identify CLS sources.</strong> Expand "Avoid large layout shifts." It shows which elements shifted and by how much. Common culprits: images without dimensions, late-loading fonts, dynamically injected content.</p>\n<p><strong>Step 4: Identify TBT/INP sources.</strong> Expand "Avoid long main-thread tasks." It shows which scripts block the main thread and for how long. Long tasks over 50ms are the ones to fix.</p>\n<p><strong>Step 5: Prioritize.</strong> Which metric is furthest from passing? That is your Saturday focus.</p>',
                },
                {
                    "heading": "Saturday Morning: Fix LCP",
                    "content": '<p>LCP failures are caused by slow-loading hero images, render-blocking CSS/JS, or slow server response. Fix them in this order:</p>\n<p><strong>Optimize the LCP image.</strong> If your LCP element is an image:</p>\n<pre><code>&lt;!-- Before: 800KB JPEG, no sizing --&gt;\n&lt;img src="hero.jpg" alt="..."&gt;\n\n&lt;!-- After: WebP, sized, prioritized --&gt;\n&lt;img src="hero.webp" alt="..."\n     width="1200" height="600"\n     fetchpriority="high"\n     srcset="hero-400.webp 400w, hero-800.webp 800w, hero-1200.webp 1200w"\n     sizes="100vw"&gt;</code></pre>\n<p>Convert to WebP (25-35% smaller). Add explicit dimensions. Add <code>fetchpriority="high"</code>. Add srcset for responsive sizes. Target: hero image under 100KB.</p>\n<p><strong>Eliminate render-blocking CSS.</strong> If your LCP is a text element blocked by CSS:</p>\n<pre><code>&lt;!-- Inline critical CSS in head --&gt;\n&lt;style&gt;\n  /* Only the CSS needed for above-the-fold content */\n  body { font-family: system-ui; color: #333; }\n  .hero { padding: 4rem 0; }\n  .hero h1 { font-size: 2.5rem; }\n&lt;/style&gt;\n\n&lt;!-- Load full CSS asynchronously --&gt;\n&lt;link rel="preload" href="styles.css" as="style"\n      onload="this.onload=null;this.rel=\'stylesheet\'"&gt;</code></pre>\n<p><strong>Reduce TTFB.</strong> If your server response is over 600ms, enable server-side caching or switch to a CDN. For WordPress: install WP Rocket. For any platform: put Cloudflare in front (free).</p>',
                },
                {
                    "heading": "Saturday Afternoon: Fix CLS",
                    "content": '<p>CLS fixes are usually quick. The goal is to prevent elements from moving after they start rendering.</p>\n<p><strong>Add dimensions to all images and videos:</strong></p>\n<pre><code>&lt;!-- Before: browser does not know size --&gt;\n&lt;img src="photo.webp" alt="..."&gt;\n\n&lt;!-- After: browser reserves exact space --&gt;\n&lt;img src="photo.webp" alt="..." width="600" height="400"\n     style="max-width: 100%; height: auto;"&gt;</code></pre>\n<p><strong>Fix font loading flash:</strong></p>\n<pre><code>@font-face {\n  font-family: \'YourFont\';\n  src: url(\'font.woff2\') format(\'woff2\');\n  font-display: swap; /* Shows fallback instantly */\n}</code></pre>\n<p><strong>Reserve space for dynamic content.</strong> If ads, cookie banners, or embeds inject content after load, give them a fixed-height container:</p>\n<pre><code>.ad-slot { min-height: 250px; }\n.cookie-banner { position: fixed; /* does not shift layout */ }</code></pre>\n<p><strong>Do not inject content above existing content.</strong> If a notification bar appears at the top of the page, it pushes everything down. Use <code>position: fixed</code> or <code>position: sticky</code> instead so it overlays without shifting.</p>',
                },
                {
                    "heading": "Sunday Morning: Fix INP/TBT",
                    "content": '<p>INP (Interaction to Next Paint) measures how fast the page responds to clicks and taps. TBT (Total Blocking Time) in lab tests correlates with INP in the field. Both are caused by JavaScript blocking the main thread.</p>\n<p><strong>Defer non-critical JavaScript:</strong></p>\n<pre><code>&lt;!-- Before: blocks parsing --&gt;\n&lt;script src="analytics.js"&gt;&lt;/script&gt;\n\n&lt;!-- After: executes after HTML parsed --&gt;\n&lt;script src="analytics.js" defer&gt;&lt;/script&gt;</code></pre>\n<p><strong>Load third-party scripts on interaction:</strong></p>\n<pre><code>// Load chat widget only when user scrolls\nlet chatLoaded = false;\nwindow.addEventListener(\'scroll\', function() {\n  if (!chatLoaded) {\n    chatLoaded = true;\n    const s = document.createElement(\'script\');\n    s.src = \'https://chat-widget.example.com/widget.js\';\n    document.body.appendChild(s);\n  }\n}, { once: true });</code></pre>\n<p><strong>Break up long tasks.</strong> If a script takes 200ms to execute, split it into smaller chunks using <code>requestIdleCallback</code> or <code>setTimeout(fn, 0)</code> to yield the main thread between chunks.</p>\n<p><strong>Remove heavy plugins.</strong> On WordPress, install the Query Monitor plugin and check which plugins add the most JavaScript. Remove or replace the heaviest ones.</p>',
                },
                {
                    "heading": "Sunday Afternoon: Verify and Monitor",
                    "content": f'<p><strong>Re-test all 5 pages.</strong> Run each through PageSpeed Insights 3 times and average the results. Compare against your Friday baselines.</p>\n<p><strong>Check field data.</strong> Lab data (PageSpeed Insights) updates immediately. Field data (Chrome User Experience Report) takes 28 days to reflect changes. Check Google Search Console\'s Core Web Vitals report weekly for the next month.</p>\n<p><strong>Expected improvements:</strong></p>\n<ul>\n<li>Image optimization alone: 10-20 point improvement</li>\n<li>CSS/JS deferral: 5-15 point improvement</li>\n<li>CLS fixes: 0.05-0.15 CLS reduction</li>\n<li>Third-party script management: 5-10 point improvement</li>\n</ul>\n<p><strong>If you are still below 85 after all fixes:</strong> The platform is the ceiling. WordPress, Webflow, and Squarespace have architectural limits that weekend optimization cannot overcome. A rebuild to static HTML costs ${PRICING["redesign_wp_sq_wix"]["low"]:,}-{PRICING["redesign_wp_sq_wix"]["high"]:,} and delivers 90-98 permanently. <a href="/audit/">Run a free audit</a> to see the gap.</p>\n<p>For the full technical reference, read our <a href="/blog/page-speed-optimization-guide/">complete page speed optimization guide</a> or the <a href="/blog/website-speed-checklist-47-items/">47-item speed checklist</a>.</p>',
                },
            ],
            "faqs": [
                {"question": "Can I really fix Core Web Vitals in one weekend?", "answer": "For most sites, yes. The fixes (image optimization, CSS/JS deferral, dimension attributes, font-display) are straightforward. Complex sites with heavy JavaScript frameworks may need more time for the INP fixes."},
                {"question": "Which Core Web Vital is hardest to fix?", "answer": "INP (Interaction to Next Paint) is hardest because it requires reducing JavaScript execution time, which often means removing or restructuring code. LCP and CLS fixes are usually simpler (image optimization, dimension attributes)."},
                {"question": "Do I need a developer to fix Core Web Vitals?", "answer": "Basic fixes (image compression, adding dimensions, defer attributes) can be done by anyone with CMS access. Advanced fixes (critical CSS inlining, script splitting, third-party management) typically require a developer."},
                {"question": "How long until Google reflects my improvements?", "answer": "Lab data (PageSpeed Insights) reflects changes immediately. Field data (what Google uses for rankings) uses a 28-day rolling average from real Chrome users. Expect ranking impact 4-8 weeks after fixes are deployed."},
            ],
        },
        {
            "slug": "website-migration-checklist-30-steps",
            "title": "Website Migration Checklist: 30 Steps to Switch Platforms Without Losing Rankings",
            "description": "A 30-step checklist for migrating from WordPress, Webflow, or any CMS to a new platform. Pre-migration, during migration, and post-migration steps to preserve SEO rankings.",
            "h1": "Website Migration Checklist: 30 Steps to Switch Platforms Without Losing Rankings",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "Why Migrations Fail",
                    "content": '<p>Most website migrations that lose rankings fail for the same reasons: changed URLs without redirects, altered meta tags, broken internal links, or missing schema markup. Every one of these is preventable with a systematic checklist.</p>\n<p>This 30-step checklist covers pre-migration (planning and documentation), during migration (building and testing), and post-migration (launch and monitoring). Follow it in order and your rankings will survive the transition. In many cases, the speed improvement from a better platform actually improves rankings within weeks.</p>\n<p>For platform-specific guidance, see our <a href="/blog/migrate-wordpress-to-static-html-without-losing-seo/">WordPress migration guide</a> and <a href="/blog/migrate-webflow-to-static-html/">Webflow migration guide</a>.</p>',
                },
                {
                    "heading": "Pre-Migration: Steps 1-10",
                    "content": '<ol>\n<li><strong>Crawl your current site.</strong> Use Screaming Frog (free under 500 URLs) to export every URL, title tag, meta description, H1, canonical URL, and internal link.</li>\n<li><strong>Export your sitemap.</strong> Save your current sitemap.xml as a baseline reference.</li>\n<li><strong>Record current PageSpeed scores.</strong> Test your top 10 pages on mobile. These are your "before" numbers.</li>\n<li><strong>Record current keyword rankings.</strong> Use Google Search Console or a rank tracker to document positions for your top 20 keywords.</li>\n<li><strong>Document all redirects.</strong> If your current site has any 301 redirects in place, document them. They need to carry over to the new platform.</li>\n<li><strong>Export CMS content.</strong> Blog posts, team bios, portfolio items, testimonials. WordPress: use the built-in XML export. Webflow: use the CMS API or manual copy.</li>\n<li><strong>Download all media files.</strong> Images, PDFs, videos. Organize by page so nothing is missed.</li>\n<li><strong>Document schema markup.</strong> If your site has Organization, LocalBusiness, Article, FAQ, or other structured data, capture it for replication.</li>\n<li><strong>List all third-party integrations.</strong> Forms (Formspree, HubSpot), analytics (GA4), tracking (Meta Pixel), chat, booking tools. Each needs reconnecting on the new site.</li>\n<li><strong>Set a launch date.</strong> Tuesday or Wednesday. Not Friday. You want 3 business days to monitor and fix issues before the weekend.</li>\n</ol>',
                },
                {
                    "heading": "During Migration: Steps 11-20",
                    "content": '<ol start="11">\n<li><strong>Match URL structure exactly.</strong> If the old site used <code>/about/</code>, the new site must serve <code>/about/</code>. Not <code>/about-us/</code>. Not <code>/about</code> without the trailing slash. Exact match.</li>\n<li><strong>Replicate all title tags exactly.</strong> Copy from your crawl export. Do not "improve" them during migration. Optimize after the migration stabilizes (4-6 weeks).</li>\n<li><strong>Replicate all meta descriptions exactly.</strong> Same principle. Preservation first, optimization later.</li>\n<li><strong>Replicate heading structure.</strong> Same H1 on each page. Same H2 organization. Google uses heading structure as a content signal.</li>\n<li><strong>Replicate schema markup.</strong> Copy structured data from the old site or improve it. Use the same @type, same properties. Test with Google\'s Rich Results Test.</li>\n<li><strong>Set up 301 redirects for changed URLs.</strong> Any URL that changed needs a 301 redirect from old to new. WordPress admin URLs (/wp-admin/, /wp-login.php), feed URLs, and pagination URLs all need redirects.</li>\n<li><strong>Reconnect third-party integrations.</strong> GA4 tracking code, Meta Pixel, form endpoints, chat widgets. Test each one on the staging site.</li>\n<li><strong>Optimize images during rebuild.</strong> Convert to WebP, add srcset, add explicit dimensions. This is the one improvement you should make during migration because it compounds with the platform speed improvement.</li>\n<li><strong>Test on a staging URL.</strong> Deploy the new site to a staging domain. Crawl it with Screaming Frog. Compare every URL and meta tag against the original crawl export.</li>\n<li><strong>Fix all discrepancies.</strong> Every missing URL, changed title, or broken link found in step 19 must be fixed before launch.</li>\n</ol>',
                },
                {
                    "heading": "Post-Migration: Steps 21-30",
                    "content": f'<ol start="21">\n<li><strong>Update DNS.</strong> Point your domain to the new hosting. Propagation takes 1-24 hours. During propagation, some visitors see the old site, some see the new one.</li>\n<li><strong>Submit new sitemap to Search Console.</strong> Go to Google Search Console > Sitemaps > submit the new sitemap URL. Google will re-crawl your pages within hours.</li>\n<li><strong>Request indexing for top pages.</strong> Use the URL Inspection tool in Search Console to manually request indexing for your 10 most important pages.</li>\n<li><strong>Monitor Search Console for 404 errors.</strong> Check the Coverage report daily for the first 2 weeks. Any new 404 means a URL was missed in migration.</li>\n<li><strong>Monitor keyword rankings daily.</strong> Minor fluctuations (1-3 positions) are normal during re-indexing. Drops of 10+ positions indicate a migration issue.</li>\n<li><strong>Verify all forms work.</strong> Submit a test through every form on the site. Verify the submission arrives at the correct email.</li>\n<li><strong>Verify all tracking fires.</strong> Check GA4 real-time report, Meta Events Manager, and any other tracking tools. Confirm events are recording.</li>\n<li><strong>Run PageSpeed on all key pages.</strong> Record your "after" scores. Compare against the pre-migration baselines from step 3.</li>\n<li><strong>Check Core Web Vitals in Search Console.</strong> The report uses a 28-day rolling average. Check weekly for the first month. All pages should move from "poor" or "needs improvement" to "good" as the faster site accumulates field data.</li>\n<li><strong>Wait 4-6 weeks before optimizing.</strong> Let the migration stabilize. Do not change title tags, URLs, or meta descriptions during this period. After 4-6 weeks with stable rankings, you can begin optimizing.</li>\n</ol>\n<p>Need help with your migration? We handle steps 1-30 for every client. WordPress migrations start at ${PRICING["redesign_wp_sq_wix"]["low"]:,}. Webflow migrations start at ${PRICING["redesign_webflow"]["low"]:,}. <a href="/audit/">Start with a free audit</a> or see <a href="/pricing/">pricing</a>.</p>',
                },
            ],
            "faqs": [
                {"question": "How long does a website migration take?", "answer": "Pre-migration planning: 2-3 days. Building the new site: 1-3 weeks depending on page count. Testing and launch: 2-3 days. Post-migration monitoring: 4-6 weeks. Total active work: 2-4 weeks."},
                {"question": "Will I lose rankings during migration?", "answer": "Not if you follow this checklist. The key is preserving URLs, meta tags, and redirects. Most properly executed migrations see rankings stabilize within 2 weeks and improve within 6 weeks due to the speed improvement."},
                {"question": "What is the riskiest part of a migration?", "answer": "Missing redirects for changed URLs. Every URL that returns a 404 (instead of redirecting to the new location) loses whatever rankings it had. The fix is thorough crawling before and after migration to catch every URL."},
                {"question": "Can I migrate from any platform?", "answer": f"Yes. The checklist applies to migrations from WordPress, Webflow, Squarespace, Wix, Drupal, or any CMS to any destination platform. We specialize in migrating to static HTML for maximum speed. Pricing starts at ${PRICING['redesign_wp_sq_wix']['low']:,}."},
            ],
        },
    ]
