"""7 event marketing blog articles for SharpPages."""


def get_event_marketing_articles(PRICING):
    """Return 7 event marketing blog article dicts."""
    return [
        {
            "slug": "event-registration-page-best-practices",
            "title": "Event Registration Page Best Practices: What Converts",
            "description": "Practical best practices for event registration pages that convert. Covers form design, mobile optimization, social proof, urgency, and real conversion benchmarks.",
            "h1": "Event Registration Page Best Practices: What Converts",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "Why Most Event Registration Pages Fail",
                    "content": '<p>Most event registration pages lose half their potential attendees before the form is submitted. The reasons are predictable: too many form fields, slow load times, unclear event details, and no mobile optimization. Fixing these is not complicated, but it requires knowing which elements actually affect conversion rates and which are cosmetic.</p>\n<p>The average event registration page converts at 10-15% of visitors. Well-optimized pages convert at 25-40%. That gap represents real revenue for paid events and real attendance for free ones. Everything in this guide is based on patterns from pages we have built and measured, not theoretical best practices.</p>',
                },
                {
                    "heading": "Form Design: The Single Biggest Conversion Factor",
                    "content": '<p>The registration form is where most pages lose people. Every additional field reduces completion rates by 5-10%. Here is what to keep and what to cut.</p>\n<h3>Fields That Belong on Every Registration Form</h3>\n<ul>\n<li><strong>Full name.</strong> One field or two (first/last). Two fields are slightly better for data quality but one field reduces friction.</li>\n<li><strong>Email address.</strong> Your primary communication channel for confirmations, reminders, and follow-ups.</li>\n<li><strong>Ticket type or session selection.</strong> Only if you have multiple options. Use radio buttons, not a dropdown, for 4 or fewer options.</li>\n</ul>\n<h3>Fields That Belong on Some Registration Forms</h3>\n<ul>\n<li><strong>Phone number.</strong> Only if you need it for day-of communication (e.g., outdoor events, multi-venue conferences). Mark it optional if you include it.</li>\n<li><strong>Company name and title.</strong> Only for B2B events where you need to qualify attendees. Skip for consumer events.</li>\n<li><strong>Dietary restrictions.</strong> Only if you are serving food. Combine with a single "special requirements" field instead of separate allergy checkboxes.</li>\n</ul>\n<h3>Fields That Hurt Conversion</h3>\n<ul>\n<li><strong>Address.</strong> Unless you are shipping physical tickets, you do not need it. Even for paid events, the payment processor collects billing info separately.</li>\n<li><strong>"How did you hear about us?"</strong> This field is for your analytics, not the attendee. Use UTM parameters instead.</li>\n<li><strong>Company size, industry, revenue.</strong> Qualification questions that belong in a follow-up survey, not the registration form.</li>\n</ul>\n<p>The rule is simple: every field must serve the attendee, not just the organizer. If you need additional data, collect it after registration via a follow-up email.</p>',
                },
                {
                    "heading": "Page Structure That Converts",
                    "content": '<p>The layout of your registration page matters as much as the form itself. Here is the structure that consistently produces the highest conversion rates.</p>\n<h3>Above the Fold: The Decision Zone</h3>\n<p>Everything a visitor needs to decide "yes, I want to attend" should be visible without scrolling:</p>\n<ul>\n<li><strong>Event name</strong> as the H1. Clear, specific, no clever taglines.</li>\n<li><strong>Date, time, and location.</strong> Visible immediately, not buried in body text. Include timezone for virtual events.</li>\n<li><strong>Price</strong> (or "Free"). Do not make people hunt for the cost.</li>\n<li><strong>Primary CTA button.</strong> "Register Now" or "Save Your Spot." Visible above the fold.</li>\n</ul>\n<p>That is four elements. Not a hero video. Not a speaker carousel. Not a paragraph about the organizer. The decision zone should be scannable in 5 seconds.</p>\n<h3>Below the Fold: The Persuasion Zone</h3>\n<p>Visitors who scroll past the fold need more information before committing:</p>\n<ul>\n<li><strong>Agenda or session details.</strong> What will attendees learn or experience? Be specific. "Networking lunch" means nothing. "45-minute roundtable with 6 CISOs from Fortune 500 companies" is a reason to attend.</li>\n<li><strong>Speaker bios and headshots.</strong> For speaker-driven events, this is the primary conversion driver below the fold. Include title, company, and one sentence about what makes them worth hearing.</li>\n<li><strong>Social proof.</strong> Past attendee counts ("Sold out in 2025 with 400 attendees"), testimonials, or logos of companies whose employees attended.</li>\n<li><strong>Second CTA.</strong> Repeat the registration button after the persuasion section. Visitors should never need to scroll back up to register.</li>\n</ul>',
                },
                {
                    "heading": "Mobile Optimization Is Not Optional",
                    "content": f'<p>40-60% of event registration page traffic comes from mobile devices, depending on how you promote the event. Social media ads (Facebook, Instagram, LinkedIn) send almost exclusively mobile traffic. Email campaigns are roughly 50/50.</p>\n<p>Mobile optimization for registration pages means:</p>\n<ul>\n<li><strong>Single-column layout.</strong> No side-by-side form fields on mobile. Stack everything vertically.</li>\n<li><strong>Large tap targets.</strong> Buttons at least 48px tall. Form fields with enough padding to tap without precision.</li>\n<li><strong>Minimal scrolling to the form.</strong> On mobile, the form should be reachable within 1-2 thumb swipes. Consider placing a "Jump to registration" button fixed at the bottom of the mobile viewport.</li>\n<li><strong>Fast load time.</strong> Mobile connections are slower than desktop. Target under 2 seconds on 4G. This means no hero videos, compressed images, and minimal JavaScript.</li>\n</ul>\n<p>Test your registration page on an actual phone before launching. Desktop preview in Chrome DevTools is not the same as using the page on a real device with a real thumb.</p>\n<p>Our <a href="/event-registration/">event registration sites</a> are built mobile-first with sub-second load times. First event site starts at ${PRICING["event_first"]["low"]:,}.</p>',
                },
                {
                    "heading": "Urgency and Scarcity: Use Them Honestly",
                    "content": '<p>Urgency (time-limited) and scarcity (quantity-limited) are powerful conversion tools when they are real. When they are fake, they destroy trust.</p>\n<h3>Real Urgency</h3>\n<ul>\n<li><strong>Early bird pricing with a real deadline.</strong> "Register by March 15 for $99 (regular price $149)." Show the deadline prominently. When the deadline passes, actually raise the price.</li>\n<li><strong>Registration closing date.</strong> If you need a final count for catering or venue, close registration 48-72 hours before the event and say so.</li>\n</ul>\n<h3>Real Scarcity</h3>\n<ul>\n<li><strong>Venue capacity.</strong> If the room holds 100 people, say "Limited to 100 attendees" and show a progress indicator when you pass 70%.</li>\n<li><strong>Table/group limits.</strong> For dinner events or roundtables: "Only 8 seats per table, 5 tables remaining."</li>\n</ul>\n<h3>What Not to Do</h3>\n<ul>\n<li>Fake countdown timers that reset when you revisit the page.</li>\n<li>"Only 3 spots left!" when you have unlimited virtual seats.</li>\n<li>Urgency language for events months away. It feels desperate, not urgent.</li>\n</ul>\n<p>Honest urgency works because it gives people a reason to act now instead of bookmarking and forgetting. Dishonest urgency works once and then people stop believing you.</p>',
                },
                {
                    "heading": "Confirmation and Follow-Up: Where Most Pages Stop Too Early",
                    "content": '<p>The registration form submission is not the end of the conversion process. What happens immediately after registration affects show-up rates, which are the metric that actually matters.</p>\n<h3>Confirmation Page</h3>\n<p>After successful registration, show a confirmation page with:</p>\n<ul>\n<li>Clear "You\'re registered!" message</li>\n<li>Event details repeated (date, time, location, any prep instructions)</li>\n<li>"Add to Calendar" links (Google Calendar, iCal, Outlook). Generate these automatically. Most registrants will not manually add the event.</li>\n<li>Social sharing buttons. "Invite a colleague" works better than generic "Share on LinkedIn."</li>\n</ul>\n<h3>Confirmation Email</h3>\n<p>Send immediately. Include the same information as the confirmation page plus:</p>\n<ul>\n<li>A calendar file (.ics) attachment</li>\n<li>Parking, directions, or virtual event login details</li>\n<li>Contact information for questions</li>\n</ul>\n<h3>Reminder Sequence</h3>\n<p>For free events, expect 30-50% no-show rates. Reminders reduce this significantly:</p>\n<ul>\n<li><strong>1 week before:</strong> Reminder with updated agenda or speaker announcement to re-sell the event.</li>\n<li><strong>1 day before:</strong> Logistics email. Parking, dress code, what to bring.</li>\n<li><strong>Morning of (for afternoon/evening events):</strong> Short "See you tonight" email with address and time only.</li>\n</ul>\n<p>Each reminder reduces no-shows by 5-10%. A three-email sequence typically improves attendance by 15-25% compared to confirmation-only.</p>',
                },
                {
                    "heading": "Conversion Benchmarks to Measure Against",
                    "content": f'<p>Here are realistic conversion benchmarks based on event registration pages we have built and measured:</p>\n<ul>\n<li><strong>Free local event:</strong> 20-35% visitor-to-registration conversion rate</li>\n<li><strong>Free virtual event:</strong> 25-45% conversion rate (lower friction)</li>\n<li><strong>Paid event under $100:</strong> 8-18% conversion rate</li>\n<li><strong>Paid event $100-$500:</strong> 4-10% conversion rate</li>\n<li><strong>Paid event $500+:</strong> 2-6% conversion rate</li>\n</ul>\n<p>If your page is significantly below these ranges, the issue is usually one of: too many form fields, unclear event value proposition, slow page load, or poor mobile experience. Fix those four things before worrying about button colors or headline copy.</p>\n<p>If your page is at or above these ranges and you want more registrations, the lever is traffic, not conversion optimization. Increase promotion spend or reach.</p>\n<p>We build event registration pages that consistently hit the upper end of these ranges. Static HTML, sub-second load, mobile-first, optimized forms. Starting at ${PRICING["event_first"]["low"]:,} for your first event, ${PRICING["event_clone"]["low"]:,} for recurring events cloned from the first. <a href="/audit/">Run a free audit</a> on your current page to see what is costing you registrations.</p>',
                },
            ],
            "faqs": [
                {"question": "How many fields should an event registration form have?", "answer": "3-5 fields maximum for most events. Name, email, and ticket type are the essentials. Every additional field beyond 5 reduces completion rates by 5-10%. Collect supplementary information in a post-registration survey, not the signup form."},
                {"question": "What is a good conversion rate for an event registration page?", "answer": "For free events, 20-35% is typical. For paid events under $100, 8-18% is the benchmark. Well-optimized pages with fast load times, minimal form fields, and clear event details consistently hit the upper end of these ranges."},
                {"question": "Should I use Eventbrite or a custom registration page?", "answer": f"Eventbrite is fine for small, one-off events where you need payment processing and do not want to build anything. For branded events, recurring events, or events where you need pixel tracking for ad retargeting, a custom page performs significantly better. Custom event sites start at ${PRICING['event_first']['low']:,}."},
                {"question": "How do I reduce no-shows for free events?", "answer": "Send a three-email reminder sequence: 1 week before (re-sell the value), 1 day before (logistics), and morning-of (time and location only). Include calendar file attachments in the confirmation email. This sequence typically reduces no-shows by 15-25%."},
                {"question": "Does page speed affect event registration conversion?", "answer": "Yes. Pages that load in under 2 seconds convert 15-25% better than pages that take 4+ seconds. Mobile users are especially sensitive to load time because they are often registering from social media ads on cellular connections."},
            ],
        },
        {
            "slug": "event-landing-page-examples",
            "title": "Event Landing Page Examples with Conversion Data",
            "description": "Real event landing page patterns with conversion data. Breakdown of page structures, form designs, and layouts that produce measurable registration results.",
            "h1": "Event Landing Page Examples with Conversion Data",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "Why Examples Without Data Are Useless",
                    "content": '<p>Most "event landing page examples" articles show you pretty screenshots with no performance data. That is like reviewing restaurants by photographing the menu. The question is not "does it look good?" The question is "does it convert?"</p>\n<p>This guide breaks down event landing page patterns by type, structure, and the conversion metrics they typically produce. We are not naming specific clients, but these patterns are drawn from event pages we have built and measured across dozens of events.</p>',
                },
                {
                    "heading": "Pattern 1: The Minimal Free Event Page",
                    "content": '<p>This pattern works for free community events, meetups, and workshops where the barrier to attendance is time, not money.</p>\n<h3>Structure</h3>\n<ul>\n<li>H1: Event name</li>\n<li>Subheading: Date, time, location (all in one line)</li>\n<li>2-3 sentence description of what attendees will learn or experience</li>\n<li>Registration form: name + email only</li>\n<li>Below form: brief speaker bio or host introduction</li>\n<li>Footer: organizer contact info</li>\n</ul>\n<h3>What Makes It Work</h3>\n<p>Minimal friction. A visitor can read the page and register in under 30 seconds. There is nothing to distract, nothing to scroll past, and the form asks for the absolute minimum.</p>\n<h3>Typical Results</h3>\n<ul>\n<li>Conversion rate: 30-45% from direct traffic, 20-30% from social ads</li>\n<li>Average time on page: 40-60 seconds</li>\n<li>Mobile conversion rate: within 5% of desktop (minimal page means minimal mobile issues)</li>\n</ul>\n<p>This pattern underperforms for events that need to "sell" the value proposition. If the event name and a 2-sentence description are not enough to motivate registration, you need more content below the fold. But for events with built-in audiences (company meetups, recurring series, community events), less is more.</p>',
                },
                {
                    "heading": "Pattern 2: The Speaker-Driven Conference Page",
                    "content": '<p>This pattern works for conferences, summits, and events where the speakers are the primary draw.</p>\n<h3>Structure</h3>\n<ul>\n<li>H1: Conference name + year</li>\n<li>Date, location, price prominently displayed</li>\n<li>Primary CTA: "Register Now" button above the fold</li>\n<li>Speaker grid: headshots, names, titles, companies. 6-12 speakers in a responsive grid</li>\n<li>Agenda: time slots with session titles and speakers. Collapsible for multi-track events</li>\n<li>Social proof section: past year stats ("400 attendees from 120 companies"), testimonials</li>\n<li>Pricing table: early bird vs. regular vs. VIP tiers</li>\n<li>Second CTA at bottom of page</li>\n<li>FAQ section</li>\n</ul>\n<h3>What Makes It Work</h3>\n<p>Speakers sell conferences. The speaker grid is the highest-engagement section on conference pages. Headshots with recognizable company logos create instant credibility. The agenda provides enough detail for attendees to justify the time investment (and get manager approval for the expense).</p>\n<h3>Typical Results</h3>\n<ul>\n<li>Conversion rate: 5-12% for paid conferences ($200-$500)</li>\n<li>Average time on page: 3-5 minutes (visitors read the full agenda)</li>\n<li>Speaker section scroll depth: 85%+ of visitors reach the speaker grid</li>\n<li>Early bird pricing accounts for 40-60% of total registrations</li>\n</ul>\n<p>The biggest conversion killer for conference pages is a slow-loading speaker section. 12 unoptimized headshot images can add 3-5 MB to page weight. Compress headshots to 20-30KB each and use lazy loading for images below the first row.</p>',
                },
                {
                    "heading": "Pattern 3: The Dinner Event Page (B2B)",
                    "content": '<p>This pattern works for intimate B2B events: executive dinners, CME dinners, roundtable discussions, and hosted networking events with 20-50 attendees.</p>\n<h3>Structure</h3>\n<ul>\n<li>H1: Event title (often includes "Executive Dinner" or "Roundtable")</li>\n<li>Date, time, venue name and city. The venue name matters for upscale events.</li>\n<li>"Complimentary" or specific price. B2B dinners are often free for qualified attendees.</li>\n<li>1-2 paragraph event description emphasizing exclusivity and peer quality</li>\n<li>Topic or discussion agenda (3-5 bullet points, not a full schedule)</li>\n<li>Registration form: name, email, title, company (4 fields). Title and company are needed because these events qualify attendees.</li>\n<li>Venue photo or map</li>\n<li>Host/sponsor logo</li>\n</ul>\n<h3>What Makes It Work</h3>\n<p>Exclusivity is the conversion driver for dinner events. "An evening of conversation with 20 senior technology leaders" is more compelling than "Free dinner event." The venue and the attendee profile are the selling points, not the content agenda.</p>\n<h3>Typical Results</h3>\n<ul>\n<li>Conversion rate from targeted traffic (email invitations, LinkedIn ads to matched audiences): 15-25%</li>\n<li>Conversion rate from broad traffic: 3-8% (most visitors are not qualified)</li>\n<li>Average time on page: 1.5-2.5 minutes</li>\n<li>Title/company field completion rate: 90%+ (attendees expect to be qualified)</li>\n</ul>\n<p>The key metric for dinner events is not registration volume but registration quality. A page that converts 25% but attracts the wrong audience is worse than one that converts 10% of the right people. Tight ad targeting matters more than page optimization for this pattern.</p>',
                },
                {
                    "heading": "Pattern 4: The Multi-Day Conference with Tracks",
                    "content": '<p>This pattern works for large conferences with multiple tracks, workshops, and networking sessions spanning 2-3 days.</p>\n<h3>Structure</h3>\n<ul>\n<li>H1: Conference name + year + city</li>\n<li>Hero section with date range, venue, and primary CTA</li>\n<li>Conference overview: 2-3 paragraphs on theme and value proposition</li>\n<li>Track overview: card layout showing each track (e.g., "Engineering Track," "Business Track," "Workshop Track") with brief descriptions</li>\n<li>Keynote speakers: 3-5 featured speakers with larger bios</li>\n<li>Full speaker grid: remaining speakers in a compact grid</li>\n<li>Pricing tiers: often "Conference Only," "Conference + Workshop," "All Access"</li>\n<li>Venue and travel section: hotel blocks, directions, nearby airports</li>\n<li>Sponsor logos</li>\n<li>FAQ section</li>\n</ul>\n<h3>What Makes It Work</h3>\n<p>Multi-day conferences require more content because the purchase decision is larger (higher ticket price, travel costs, 2-3 days out of office). Visitors need enough detail to build a business case for attending. The track overview helps visitors quickly identify whether the conference is relevant to their specific role.</p>\n<h3>Typical Results</h3>\n<ul>\n<li>Conversion rate: 3-7% for conferences priced at $500-$2,000</li>\n<li>Average time on page: 5-8 minutes (heavy content consumption before a large purchase)</li>\n<li>Multiple visits before registration: 2.4 average (people bookmark and return)</li>\n<li>Return visitor conversion rate: 15-25% (much higher than first-visit rate)</li>\n</ul>\n<p>For multi-day conferences, optimize for return visits. Save visitor state (which tracks they clicked on), and consider a "Save my spot" soft-commit that captures an email for follow-up before full registration. Many attendees need manager approval before purchasing, so the path from interest to registration spans multiple sessions.</p>',
                },
                {
                    "heading": "Pattern 5: The Recurring Event Series Page",
                    "content": f'<p>This pattern works for monthly meetups, quarterly dinners, webinar series, and other recurring events.</p>\n<h3>Structure</h3>\n<ul>\n<li>H1: Series name (not individual event name)</li>\n<li>Series description: what attendees can expect at every event</li>\n<li>Upcoming events: list of next 3-5 events with dates, topics, and individual registration links</li>\n<li>Past events: thumbnails or titles showing the series history (builds credibility)</li>\n<li>Subscribe option: "Get notified about future events" email capture for people not ready to register for a specific date</li>\n</ul>\n<h3>What Makes It Work</h3>\n<p>The series page serves two audiences: people ready to register for a specific upcoming event (send them to the individual event page) and people discovering the series for the first time who need to understand the concept before committing to a date. The subscribe option captures the second audience for future conversion.</p>\n<h3>Typical Results</h3>\n<ul>\n<li>Individual event registration rate: similar to Pattern 1 or 3 depending on event type</li>\n<li>Series subscription rate: 8-15% of visitors subscribe for notifications</li>\n<li>Subscriber-to-registrant conversion: 25-40% of subscribers register for the next event</li>\n</ul>\n<p>For recurring events, the series page is your most important long-term asset. It builds organic search authority over time (unlike individual event pages that are only relevant for a few weeks). Internal link from each individual event page back to the series page to consolidate SEO value.</p>\n<p>We build recurring event systems where the first site costs ${PRICING["event_first"]["low"]:,}-${PRICING["event_first"]["high"]:,} and each subsequent event clone costs just ${PRICING["event_clone"]["low"]:,}-${PRICING["event_clone"]["high"]:,}. <a href="/event-registration/">See our event registration service</a>.</p>',
                },
                {
                    "heading": "Applying These Patterns to Your Event",
                    "content": f'<p>Choose your pattern based on event type, not personal preference:</p>\n<ul>\n<li><strong>Free community/meetup event:</strong> Pattern 1 (Minimal)</li>\n<li><strong>Speaker-driven single-day conference:</strong> Pattern 2 (Speaker-Driven)</li>\n<li><strong>B2B dinner or roundtable:</strong> Pattern 3 (Dinner Event)</li>\n<li><strong>Multi-day conference:</strong> Pattern 4 (Multi-Day)</li>\n<li><strong>Recurring event series:</strong> Pattern 5 (Series Page) plus Pattern 1 or 3 for individual events</li>\n</ul>\n<p>Then optimize the four elements that affect conversion most: form field count (fewer is better), page load speed (under 2 seconds), mobile layout (single column, large targets), and above-the-fold clarity (event name, date, price, CTA visible without scrolling).</p>\n<p>Every pattern above can be built as a fast-loading static HTML page with no platform overhead. <a href="/audit/">Run a free audit</a> on your current event page or <a href="/event-registration/">see our event registration service</a> to get started.</p>',
                },
            ],
            "faqs": [
                {"question": "What conversion rate should I expect from an event landing page?", "answer": "Free events: 20-35%. Paid events under $100: 8-18%. Paid events $100-$500: 4-10%. Paid multi-day conferences: 3-7%. These are visitor-to-registration rates. The biggest factors are form length, page speed, and how well the page communicates event value."},
                {"question": "Should I put the registration form on the landing page or a separate page?", "answer": "On the same page for free and low-cost events. The fewer clicks between interest and registration, the better. For high-cost events ($500+), a separate form page is acceptable because the decision process is longer and visitors expect a multi-step flow."},
                {"question": "How important are speaker photos on event landing pages?", "answer": "Very important for speaker-driven events. Pages with headshots and company logos convert 15-20% better than pages with text-only speaker lists. Compress images to 20-30KB each and lazy-load below the first row to maintain page speed."},
                {"question": "How many event landing page patterns should I test?", "answer": "Do not A/B test page patterns for individual events. The traffic volume is usually too low for statistical significance. Instead, apply the pattern that matches your event type, optimize the form and load speed, and measure results over multiple events in a series."},
                {"question": "What is the most common mistake on event landing pages?", "answer": "Burying the date, time, and price below the fold. Visitors need three things to decide if they are interested: what is the event, when is it, and what does it cost. If any of those require scrolling, you are losing people who would have registered."},
            ],
        },
        {
            "slug": "eventbrite-vs-custom-registration-page",
            "title": "Eventbrite vs Custom Registration: When to DIY",
            "description": "Honest comparison of Eventbrite vs custom event registration pages. Covers cost, conversion, branding, tracking, and when each option makes sense.",
            "h1": "Eventbrite vs Custom Registration: When to DIY",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "The Real Tradeoff",
                    "content": '<p>Eventbrite is convenient. You can publish an event page in 20 minutes with built-in payment processing, ticket management, and email reminders. For many events, that is enough.</p>\n<p>But Eventbrite has costs that are not obvious until you scale: platform fees (3.7% + $1.79 per ticket on paid events), limited branding (your event lives on eventbrite.com, not yourdomain.com), restricted tracking (no custom pixel placement, limited UTM support), and a generic attendee experience that looks like every other Eventbrite page.</p>\n<p>The question is not "which is better?" The question is "which is better for your situation?" Here is a framework for deciding.</p>',
                },
                {
                    "heading": "When Eventbrite Is the Right Choice",
                    "content": '<p>Eventbrite wins when convenience matters more than optimization. Specific scenarios:</p>\n<ul>\n<li><strong>One-off events with no follow-up marketing.</strong> If you are running a single event and do not plan to retarget attendees or build a recurring series, Eventbrite gets the job done with minimal effort.</li>\n<li><strong>Free events with under 100 expected attendees.</strong> Eventbrite\'s free tier (no fees for free events) makes it cost-effective for small free events. You get RSVP tracking and email reminders without building anything.</li>\n<li><strong>You need payment processing and do not have it.</strong> If you do not have Stripe or another payment processor set up, Eventbrite handles payments out of the box. Setting up your own payment processing adds complexity.</li>\n<li><strong>Your team has no web development capability.</strong> If nobody on your team can edit HTML or manage a static site deployment, Eventbrite is self-serve and requires zero technical skill.</li>\n<li><strong>Ticketing features matter.</strong> If you need QR code check-in, tiered pricing, group tickets, refund management, or waitlists, Eventbrite has these built in. Building them custom takes time and money.</li>\n</ul>',
                },
                {
                    "heading": "When a Custom Registration Page Is the Right Choice",
                    "content": f'<p>A custom page wins when performance, branding, or marketing integration matters. Specific scenarios:</p>\n<ul>\n<li><strong>You are running paid ads to drive registrations.</strong> Custom pages let you place Facebook Pixel, Google Ads tags, and conversion tracking exactly where you need them. Eventbrite limits pixel placement and fires its own tracking that muddies your attribution. For ad-driven events, this tracking gap costs you money because you cannot optimize campaigns accurately.</li>\n<li><strong>Brand experience matters.</strong> Corporate events, product launches, and client-facing events should live on your domain with your branding. An eventbrite.com URL signals "small event." Your own domain signals "our event."</li>\n<li><strong>You are building a recurring event series.</strong> Custom pages accumulate SEO value on your domain over time. Eventbrite pages do not. After 12 months of monthly events, your domain has 12 indexed event pages building authority. On Eventbrite, those pages build Eventbrite\'s authority, not yours.</li>\n<li><strong>You want to retarget visitors who did not register.</strong> With a custom page, you fire your retargeting pixel on every visitor. You can then show ads to people who visited but did not register. Eventbrite does not let you retarget visitors to your event page.</li>\n<li><strong>Page speed affects your conversion.</strong> Eventbrite pages load in 3-5 seconds. Custom static pages load in under 1 second. For ad-driven traffic where every percentage point of conversion matters, that speed difference translates directly to more registrations per ad dollar.</li>\n</ul>\n<p>Custom event sites start at ${PRICING["event_first"]["low"]:,}. For recurring events, subsequent events clone from the first at ${PRICING["event_clone"]["low"]:,}-${PRICING["event_clone"]["high"]:,}.</p>',
                },
                {
                    "heading": "The Cost Comparison",
                    "content": f'<p>Eventbrite costs are variable. Custom page costs are fixed. Here is how they compare at different scales:</p>\n<h3>Free Events</h3>\n<p>Eventbrite: $0 (free tier). Custom: ${PRICING["event_first"]["low"]:,}-${PRICING["event_first"]["high"]:,} upfront, $0 ongoing on static hosting.</p>\n<p>For free events, Eventbrite is cheaper unless you are running a recurring series where the custom page pays for itself through SEO value and retargeting capability over time.</p>\n<h3>Paid Events: 100 Tickets at $50</h3>\n<p>Eventbrite: ($1.85 + $1.79) x 100 = $364 in fees (3.7% + $1.79 per ticket). Custom with Stripe: 2.9% + $0.30 per ticket = $175 in Stripe fees. Custom page cost: ${PRICING["event_first"]["low"]:,}-${PRICING["event_first"]["high"]:,} one-time.</p>\n<p>At 100 tickets, the custom page is more expensive for a single event but cheaper for 2+ events because there are no additional platform fees beyond Stripe processing.</p>\n<h3>Paid Events: 500 Tickets at $200</h3>\n<p>Eventbrite: ($7.40 + $1.79) x 500 = $4,595 in fees. Custom with Stripe: (5.80 + 0.30) x 500 = $3,050 in Stripe fees. Custom page cost: ${PRICING["event_first"]["low"]:,}-${PRICING["event_first"]["high"]:,} one-time.</p>\n<p>At scale, Eventbrite\'s percentage-based fee model becomes expensive. The custom page saves $1,500+ per event in this scenario. For annual conferences or high-ticket events, the savings compound quickly.</p>',
                },
                {
                    "heading": "The Tracking Gap: Why It Matters for Paid Promotion",
                    "content": '<p>The single biggest practical difference between Eventbrite and custom pages is tracking control.</p>\n<p>With a custom page, you control:</p>\n<ul>\n<li><strong>Facebook Pixel placement.</strong> Fire PageView on load, ViewContent after 10 seconds (qualified visitor), and CompleteRegistration on form submit. This gives Facebook three signals to optimize your campaigns.</li>\n<li><strong>Google Analytics 4 events.</strong> Track every interaction: page scroll, form start, form abandonment, registration complete. See exactly where people drop off.</li>\n<li><strong>Retargeting audiences.</strong> Build audiences of page visitors who did not register. Show them follow-up ads. This is often the highest-ROI ad strategy for events.</li>\n<li><strong>UTM parameter handling.</strong> Track exactly which ad, email, or social post drove each registration. Attribute revenue to specific marketing channels.</li>\n</ul>\n<p>With Eventbrite, you can add a Facebook Pixel to your event page, but placement is limited to specific locations. You cannot fire custom events on timed interactions. You cannot access Eventbrite visitor data for retargeting. And UTM parameters get stripped or mangled in some flows.</p>\n<p>If you are spending $500+ on ads to drive registrations, the tracking gap on Eventbrite will cost you more in wasted ad spend than a custom page costs to build. Read our <a href="/blog/facebook-retargeting-for-events/">guide to Facebook retargeting for events</a> for the full pixel setup.</p>',
                },
                {
                    "heading": "The Hybrid Approach",
                    "content": f'<p>You do not have to choose one or the other. A common approach is to use a custom landing page for marketing and Eventbrite for ticketing:</p>\n<ol>\n<li>Build a custom landing page on your domain with full tracking and branding.</li>\n<li>The CTA button links to an Eventbrite checkout page for payment processing.</li>\n<li>You get: branded experience, full pixel tracking, retargeting capability, and Eventbrite\'s ticketing infrastructure.</li>\n</ol>\n<p>The tradeoff is that you lose some conversion when visitors click through to Eventbrite for checkout (every additional step costs 10-20% of visitors). But for events where Eventbrite\'s ticketing features (check-in, refunds, group tickets) are essential, this hybrid approach captures most of the benefit of both.</p>\n<p>For events where you do not need Eventbrite\'s ticketing features, skip the hybrid and go fully custom. A Stripe Checkout integration handles payments with fewer steps and lower fees. <a href="/event-registration/">Our event registration service</a> includes Stripe payment integration.</p>',
                },
            ],
            "faqs": [
                {"question": "Is Eventbrite free for free events?", "answer": "Yes. Eventbrite does not charge fees for free events. They charge 3.7% + $1.79 per ticket for paid events (as of 2026). This makes Eventbrite a reasonable choice for small free events where you do not need custom tracking or branding."},
                {"question": "Can I add Facebook Pixel to Eventbrite?", "answer": "You can add a basic Facebook Pixel to your Eventbrite page, but placement is limited. You cannot fire custom events (like timed ViewContent), cannot build full retargeting audiences of non-registrants, and some user flows strip tracking parameters. For ad-driven events, this limitation significantly impacts campaign optimization."},
                {"question": "How much does a custom event registration page cost?", "answer": f"Custom static event pages typically cost ${PRICING['event_first']['low']:,}-${PRICING['event_first']['high']:,} for the first event. Recurring events cloned from the first cost ${PRICING['event_clone']['low']:,}-${PRICING['event_clone']['high']:,}. The fixed cost becomes more economical than Eventbrite's per-ticket fees at around 100+ paid tickets per event."},
                {"question": "Can I use both Eventbrite and a custom page?", "answer": "Yes. A hybrid approach uses a custom landing page for marketing (with full tracking and branding) and links to Eventbrite for checkout and ticketing. You lose some conversion at the handoff but gain Eventbrite's ticketing features. For events needing QR code check-in or complex tiering, this hybrid works well."},
                {"question": "Does Eventbrite hurt SEO?", "answer": "Eventbrite pages rank well on their own, but the SEO value accrues to eventbrite.com, not your domain. If you run recurring events, custom pages on your domain build authority over time. After a year of monthly events, you have 12 indexed pages on your domain instead of 12 pages building Eventbrite's authority."},
            ],
        },
        {
            "slug": "event-marketing-roi-measurement",
            "title": "Event Marketing ROI: Tracking Registrations to Revenue",
            "description": "How to measure event marketing ROI from ad spend through registration to post-event revenue. Covers attribution, cost per registration, and revenue tracking methods.",
            "h1": "Event Marketing ROI: Tracking Registrations to Revenue",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "The Attribution Problem in Event Marketing",
                    "content": '<p>Event marketing has an attribution problem. Someone sees a Facebook ad, visits your registration page, registers, attends, and then becomes a customer 3 months later. Connecting that chain from ad impression to revenue is where most event marketers lose the thread.</p>\n<p>The result is that event marketing often operates on vibes. "The event felt successful." "People seemed engaged." "I think we got some leads." None of that is measurable or defensible when someone asks whether the event was worth the investment.</p>\n<p>Here is how to build a measurement system that connects event spend to revenue.</p>',
                },
                {
                    "heading": "Step 1: Track Cost Per Registration by Channel",
                    "content": '<p>Before you can measure ROI, you need to know what registrations cost. Track spend and registrations by channel:</p>\n<h3>Digital Advertising</h3>\n<p>For Facebook, Instagram, LinkedIn, and Google ads: total ad spend divided by total registrations attributed to that platform. Use UTM parameters on every ad link and track conversions through your registration page, not through the ad platform\'s estimated conversions.</p>\n<p>Why not trust the ad platform\'s numbers? Because Facebook, Google, and LinkedIn all over-count conversions. They use attribution windows (7-day click, 1-day view) that credit conversions to ads that may not have caused them. Your registration page is the source of truth for actual completions.</p>\n<p>Typical cost per registration by channel (these vary widely by event type and targeting):</p>\n<ul>\n<li><strong>Facebook/Instagram (free local event):</strong> $3-$10 per registration</li>\n<li><strong>Facebook/Instagram (paid event):</strong> $15-$50 per registration</li>\n<li><strong>LinkedIn (B2B event):</strong> $30-$80 per registration</li>\n<li><strong>Google Search (branded or event-specific):</strong> $10-$30 per registration</li>\n<li><strong>Email marketing:</strong> Near-zero marginal cost per registration (your list is a fixed investment)</li>\n</ul>\n<h3>Email Marketing</h3>\n<p>Email is usually the most cost-effective registration channel. Track opens, clicks, and registrations from each email send. Calculate cost per registration by dividing your email platform cost (divided by number of campaigns) by registrations from that campaign. For most events, email produces registrations at under $2 each.</p>\n<h3>Organic and Direct</h3>\n<p>Some registrations come from organic search, social shares, and direct URL visits. Track these in GA4 by source/medium. You cannot assign a direct cost to these channels, but they factor into overall cost per registration (total spend / total registrations across all channels).</p>',
                },
                {
                    "heading": "Step 2: Track Show-Up Rate",
                    "content": '<p>Registrations are not attendance. Your cost per attendee is higher than your cost per registration, and the gap varies by event type:</p>\n<ul>\n<li><strong>Free events:</strong> 50-70% show-up rate (30-50% no-show)</li>\n<li><strong>Low-cost paid events ($25-$100):</strong> 75-85% show-up rate</li>\n<li><strong>High-cost paid events ($200+):</strong> 85-95% show-up rate</li>\n<li><strong>Virtual events:</strong> 30-50% show-up rate (high no-show)</li>\n</ul>\n<p>Calculate cost per attendee: total marketing spend / actual attendees. This is the number that matters for ROI because only attendees can become leads or customers.</p>\n<p>To improve show-up rates, use the reminder email sequence from our <a href="/blog/event-registration-page-best-practices/">registration best practices guide</a>. Each reminder email increases show-up by 5-10%.</p>',
                },
                {
                    "heading": "Step 3: Measure Post-Event Pipeline",
                    "content": '<p>For B2B events, the revenue usually happens after the event, not at the event. You need to track what happens to attendees in the weeks and months following.</p>\n<h3>Set Up the Tracking</h3>\n<ol>\n<li><strong>Import attendee list into your CRM.</strong> Tag them with the event name and date. This creates a cohort you can track over time.</li>\n<li><strong>Track post-event engagement.</strong> How many attendees book meetings, respond to follow-up emails, or visit your website in the 30 days after the event?</li>\n<li><strong>Track pipeline creation.</strong> How many attendees entered your sales pipeline? At what deal value?</li>\n<li><strong>Track closed revenue.</strong> Over the next 3-6 months (depending on your sales cycle), how much revenue came from attendees?</li>\n</ol>\n<h3>The Timeline Problem</h3>\n<p>Event ROI takes time to materialize. A dinner event in March may generate pipeline in April and close revenue in July. If you measure ROI in April, the event looks like a loss. If you measure in August, it looks like a winner.</p>\n<p>Establish a standard measurement window based on your average sales cycle length. If your average deal closes in 90 days, measure event ROI at 120 days post-event (90 days plus buffer). Report interim metrics (pipeline created, meetings booked) in the meantime so leadership can see progress before revenue closes.</p>',
                },
                {
                    "heading": "Step 4: Calculate the Full ROI",
                    "content": '<p>Event marketing ROI has two components: direct revenue and pipeline value.</p>\n<h3>Direct Revenue ROI</h3>\n<p>For paid events where ticket sales are the revenue:</p>\n<p><strong>ROI = (Ticket Revenue - Total Event Cost) / Total Event Cost x 100</strong></p>\n<p>Total Event Cost includes: venue, catering, speakers, marketing spend (ads + email tool + design), and staff time. Do not forget staff time. If your team spent 80 hours planning and executing, that has a cost.</p>\n<h3>Pipeline ROI (B2B Events)</h3>\n<p>For B2B events where the goal is lead generation:</p>\n<p><strong>ROI = (Closed Revenue from Attendees - Total Event Cost) / Total Event Cost x 100</strong></p>\n<p>This takes months to calculate fully (see timeline problem above). In the interim, use pipeline-based projections:</p>\n<p><strong>Projected ROI = (Pipeline Value x Historical Close Rate - Total Event Cost) / Total Event Cost x 100</strong></p>\n<p>If the event generated $500K in pipeline and your historical close rate is 25%, projected revenue is $125K. If the event cost $30K, projected ROI is 317%.</p>\n<h3>Blended ROI for Events with Both Components</h3>\n<p>Some events generate both ticket revenue and B2B pipeline (conferences, for example). Calculate both separately and report them together:</p>\n<ul>\n<li>Ticket revenue: $50K</li>\n<li>Event cost: $80K</li>\n<li>Ticket-only ROI: -37.5% (the event loses money on tickets alone)</li>\n<li>Pipeline generated: $400K</li>\n<li>Projected closed revenue (at 25% close rate): $100K</li>\n<li>Total projected ROI: ($50K + $100K - $80K) / $80K = 87.5%</li>\n</ul>\n<p>Many conferences operate at a loss on ticket revenue and make money on pipeline. Knowing this upfront sets the right expectations.</p>',
                },
                {
                    "heading": "Building a Repeatable Measurement System",
                    "content": '<p>One-off ROI calculations are useful but not sustainable. Build a system:</p>\n<h3>Before Every Event</h3>\n<ul>\n<li>Set up UTM parameters for every promotion channel</li>\n<li>Place conversion tracking on the registration page (Facebook Pixel, GA4 events)</li>\n<li>Define success metrics: target registrations, target cost per registration, target attendee count</li>\n<li>Document all costs (venue, catering, ads, tools, estimated staff hours)</li>\n</ul>\n<h3>During the Event</h3>\n<ul>\n<li>Track actual attendance (check-in system or manual count)</li>\n<li>For B2B: collect leads through badge scans, business card drops, or follow-up form</li>\n</ul>\n<h3>After Every Event</h3>\n<ul>\n<li>Week 1: Final registration and attendance numbers. Cost per registration and cost per attendee by channel.</li>\n<li>Week 2-4: Post-event follow-up campaign metrics (email opens, meeting requests)</li>\n<li>Month 2-3: Pipeline created from attendees</li>\n<li>Month 4-6: Revenue closed from attendees. Final ROI calculation.</li>\n</ul>\n<h3>Quarterly Review</h3>\n<p>Compare ROI across events to identify which event types, formats, and promotion channels produce the best returns. Over 4-6 events, patterns become clear: "Executive dinners produce 3x the pipeline per dollar compared to large conferences" or "Email-driven registrations convert to customers at 2x the rate of ad-driven registrations."</p>\n<p>These patterns inform your event strategy. Without measurement, you are guessing. With measurement, you are making investment decisions based on data.</p>',
                },
                {
                    "heading": "Common Measurement Mistakes",
                    "content": '<ul>\n<li><strong>Counting registrations as the success metric.</strong> Registrations are a leading indicator, not the outcome. The outcome is attendance (for community events) or revenue (for B2B events). A high registration count with low attendance is not a success.</li>\n<li><strong>Trusting ad platform conversion counts.</strong> Facebook and Google over-count. Use your own registration page data as the source of truth. Compare platform-reported conversions to actual registrations weekly and adjust your cost-per-registration calculations accordingly.</li>\n<li><strong>Measuring ROI too early.</strong> B2B event revenue takes months to close. Reporting "ROI was negative" two weeks after the event is premature and misleading. Set a measurement window based on your sales cycle and commit to it.</li>\n<li><strong>Ignoring staff time costs.</strong> If three people spent a combined 200 hours on event planning and execution, that is real cost. At $50/hour fully loaded, that is $10,000. Excluding it makes ROI look better than reality.</li>\n<li><strong>Not tracking by channel.</strong> "Cost per registration" as a single number hides the fact that email registrations cost $2 and LinkedIn ad registrations cost $60. Channel-level tracking lets you shift budget to what works.</li>\n</ul>',
                },
            ],
            "faqs": [
                {"question": "What is a good cost per event registration?", "answer": "It depends on the event type and channel. Free local events: $3-$10 from Facebook ads. Paid events: $15-$50 from Facebook, $30-$80 from LinkedIn. Email marketing: under $2. These benchmarks vary by industry, geography, and targeting precision."},
                {"question": "How do I calculate event marketing ROI?", "answer": "ROI = (Revenue from Event - Total Event Cost) / Total Event Cost x 100. For paid events, revenue is ticket sales. For B2B events, revenue is closed deals from attendees (measured 3-6 months post-event). Include all costs: venue, catering, marketing spend, and staff time."},
                {"question": "How long should I wait to measure event ROI?", "answer": "For ticket revenue: immediately after the event. For B2B pipeline ROI: your average sales cycle length plus 30 days. If deals typically close in 90 days, measure event pipeline ROI at 120 days post-event. Report interim metrics (pipeline created, meetings booked) monthly."},
                {"question": "What show-up rate should I expect?", "answer": "Free events: 50-70%. Paid events under $100: 75-85%. Paid events over $200: 85-95%. Virtual events: 30-50%. Reminder email sequences improve show-up rates by 15-25% across all types."},
                {"question": "Should I track event ROI by marketing channel?", "answer": "Yes. Channel-level tracking reveals which channels produce the cheapest registrations and, more importantly, which produce attendees that convert to customers. Email almost always wins on cost. LinkedIn often wins on lead quality for B2B events."},
            ],
        },
        {
            "slug": "medical-device-event-marketing-guide",
            "title": "Medical Device Event Marketing: CME Dinners and Tradeshows",
            "description": "Event marketing guide for medical device companies. Covers CME dinner events, tradeshow registration, HCP compliance, and physician engagement strategies.",
            "h1": "Medical Device Event Marketing: CME Dinners and Tradeshows",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "Medical Device Events Are Different",
                    "content": '<p>Event marketing for medical device companies operates under constraints that consumer or SaaS events do not face. Sunshine Act reporting requirements, HCP (Healthcare Professional) compliance rules, CME accreditation standards, and the sheer difficulty of getting physicians to attend anything after a 12-hour shift.</p>\n<p>These constraints do not make event marketing less effective. They make it more specialized. A well-executed CME dinner in the right city with the right KOL (Key Opinion Leader) presenting can generate more qualified leads than a year of digital marketing. But the execution must account for the regulatory and practical realities.</p>',
                },
                {
                    "heading": "CME Dinner Events: The Workhorse Format",
                    "content": '<p>CME (Continuing Medical Education) dinner events are the most common and often most effective event format for medical device companies targeting physicians. The format is straightforward: an educational presentation over dinner at an upscale restaurant, typically 15-40 attendees.</p>\n<h3>Why CME Dinners Work</h3>\n<ul>\n<li><strong>CME credits motivate attendance.</strong> Physicians need continuing education credits to maintain their licenses. A CME-accredited dinner provides education they need in a format that respects their limited time.</li>\n<li><strong>Intimate setting enables conversation.</strong> Unlike tradeshows where physicians walk by a booth, dinners create 2-3 hours of sustained engagement with your clinical message.</li>\n<li><strong>KOL endorsement builds credibility.</strong> A respected surgeon or physician presenting your clinical data carries more weight than any sales deck.</li>\n<li><strong>Peer interaction is valuable.</strong> Physicians in the room learn from each other, not just the presenter. This peer dynamic is hard to replicate in digital formats.</li>\n</ul>\n<h3>Planning the Registration Page</h3>\n<p>CME dinner registration pages need specific elements that general event pages do not:</p>\n<ul>\n<li><strong>CME accreditation statement.</strong> Which accrediting body, how many credits, which specialties qualify. This is often the deciding factor for attendance.</li>\n<li><strong>Presenter credentials.</strong> Full CV summary, institution, and relevant publications. Physicians evaluate the presenter before deciding to attend.</li>\n<li><strong>Disclosure statements.</strong> Industry support disclosure is required for CME events. Include it on the registration page, not just the event materials.</li>\n<li><strong>NPI number field.</strong> Collecting NPI numbers at registration simplifies Sunshine Act reporting. Make it a required field for physician registrants.</li>\n<li><strong>Credential verification.</strong> For events limited to physicians or specific specialties, include a credential dropdown (MD, DO, NP, PA) to qualify registrants at the form level.</li>\n</ul>',
                },
                {
                    "heading": "Tradeshow and Conference Presence",
                    "content": '<p>Medical device tradeshows (AAOS, ACC, HIMSS, RSNA) are expensive. Booth space, travel, materials, and staff time for a major show can exceed $50,000-$200,000. The registration and landing page strategy for tradeshows is different from standalone events.</p>\n<h3>Pre-Show Registration Pages</h3>\n<p>Build a dedicated landing page for each tradeshow you attend. This page is not about registering for the tradeshow itself (the conference handles that). It is about getting attendees to commit to visiting your booth, attending your satellite event, or booking a meeting.</p>\n<p>Effective pre-show page elements:</p>\n<ul>\n<li><strong>Booth number and hall location.</strong> Make it easy to find you. Include a map screenshot if possible.</li>\n<li><strong>Demo schedule.</strong> Specific times when product demonstrations happen at the booth. Physicians plan their tradeshow time in advance.</li>\n<li><strong>Meeting booking.</strong> A calendar tool or simple form to schedule 1-on-1 meetings during the show. Pre-scheduled meetings convert at much higher rates than walk-up conversations.</li>\n<li><strong>Satellite event registration.</strong> If you are hosting a dinner, reception, or workshop alongside the conference, the pre-show page should drive registration for that event.</li>\n</ul>\n<h3>Post-Show Follow-Up</h3>\n<p>The pre-show registration page doubles as your follow-up tool. Everyone who registered or booked a meeting is a warm lead. Send follow-up emails within 48 hours of the show with:</p>\n<ul>\n<li>Thank you for visiting / meeting</li>\n<li>Link to any materials they requested or that were presented</li>\n<li>Clear next step (schedule a call, request a sample, connect with their rep)</li>\n</ul>',
                },
                {
                    "heading": "Compliance Requirements That Affect Event Pages",
                    "content": '<p>Medical device event marketing is regulated. Your registration page and event materials must comply with several requirements:</p>\n<h3>Sunshine Act (Open Payments)</h3>\n<p>Any transfer of value to physicians (meals, travel, honoraria) must be reported under the Physician Payments Sunshine Act. Your registration form should collect the data needed for reporting:</p>\n<ul>\n<li>Full legal name (as registered with CMS)</li>\n<li>NPI number</li>\n<li>State medical license number (helpful for verification)</li>\n<li>Specialty</li>\n</ul>\n<p>Having this data at registration time instead of collecting it after the event saves significant compliance team effort.</p>\n<h3>CME Accreditation Standards</h3>\n<p>If your event offers CME credits, the registration page must include:</p>\n<ul>\n<li>Accrediting body name and credit type</li>\n<li>Number of credits available</li>\n<li>Learning objectives</li>\n<li>Disclosure of commercial support</li>\n<li>Faculty disclosure statements</li>\n</ul>\n<p>These are not optional marketing choices. They are accreditation requirements. Missing them can result in losing CME accreditation for the event, which eliminates the primary attendance motivator.</p>\n<h3>AdvaMed Code of Ethics</h3>\n<p>The AdvaMed Code governs interactions between medical device companies and healthcare professionals. For events, key provisions include:</p>\n<ul>\n<li>Meals must be modest and conducive to education (no entertainment venues)</li>\n<li>No recreational activities as part of the event</li>\n<li>No compensation for attendee travel or lodging (with limited exceptions)</li>\n<li>Events must take place in clinical or educational settings, or venues conducive to education</li>\n</ul>\n<p>Your registration page should reflect these standards. If the venue looks too fancy or the event description sounds like entertainment, you have a compliance issue before anyone registers.</p>',
                },
                {
                    "heading": "Driving Physician Registration",
                    "content": '<p>Physicians are hard to reach and harder to convert into event attendees. Their inboxes are full, their schedules are packed, and they are skeptical of industry-sponsored events. Here is what works:</p>\n<h3>Channel Strategy</h3>\n<ul>\n<li><strong>Rep-driven invitations.</strong> The single most effective channel. A direct invitation from the physician\'s device rep, delivered in person or via personal email, converts at 3-5x the rate of any marketing channel.</li>\n<li><strong>Email to your physician database.</strong> Targeted emails to physicians in the event\'s specialty and geography. Segment by previous engagement: physicians who have attended past events convert at 30-40%, while cold contacts convert at 3-5%.</li>\n<li><strong>Paid social (Facebook/Instagram).</strong> Surprisingly effective for physician targeting. Target by job title, employer (hospital systems), and geography. Cost per registration: $20-$60 for CME dinners.</li>\n<li><strong>Medical society partnerships.</strong> Some specialty societies will promote CME events to their membership lists. The endorsement improves credibility and conversion.</li>\n</ul>\n<h3>What Motivates Registration</h3>\n<p>In order of effectiveness based on post-event surveys:</p>\n<ol>\n<li><strong>CME credits.</strong> The practical need for continuing education is the strongest motivator.</li>\n<li><strong>Presenter reputation.</strong> A nationally recognized KOL in the relevant specialty.</li>\n<li><strong>Peer networking.</strong> Opportunity to discuss cases and techniques with colleagues.</li>\n<li><strong>Clinical data.</strong> New data or technique information relevant to their practice.</li>\n<li><strong>Convenience.</strong> Close to their office or hospital. Weeknight evening timing (Tuesday or Wednesday) that does not interfere with family weekends.</li>\n</ol>',
                },
                {
                    "heading": "Measuring Medical Device Event ROI",
                    "content": '<p>Medical device event ROI is harder to measure than SaaS or consumer event ROI because the sales cycle is long (6-18 months) and the purchase involves committees, not individuals. But it is measurable.</p>\n<h3>Short-Term Metrics (0-30 days)</h3>\n<ul>\n<li><strong>Registration rate:</strong> registrations / invitations sent</li>\n<li><strong>Show-up rate:</strong> attendees / registrations</li>\n<li><strong>Post-event engagement:</strong> follow-up email opens, meeting requests, sample requests</li>\n<li><strong>Cost per attendee:</strong> total event cost / actual attendees</li>\n</ul>\n<h3>Medium-Term Metrics (1-6 months)</h3>\n<ul>\n<li><strong>Trial or evaluation requests:</strong> attendees who request product trials</li>\n<li><strong>Rep meeting conversion:</strong> attendees who schedule or take follow-up meetings with sales reps</li>\n<li><strong>Hospital committee introductions:</strong> attendees who connect you with purchasing or value analysis committees</li>\n</ul>\n<h3>Long-Term Metrics (6-18 months)</h3>\n<ul>\n<li><strong>Revenue attributed to event attendees:</strong> track purchases by attendees or their institutions</li>\n<li><strong>Account penetration:</strong> did the event help break into new hospital systems?</li>\n<li><strong>KOL development:</strong> did any attendees become advocates, speakers, or clinical trial participants?</li>\n</ul>\n<p>Tag every attendee in your CRM with the event name. Pull a revenue report on that cohort at 6, 12, and 18 months. Over time, you build a benchmark for revenue per event dollar that informs future investment decisions.</p>',
                },
                {
                    "heading": "Building an Event Marketing System for Medical Devices",
                    "content": f'<p>One-off events are expensive. A system for recurring events reduces cost per event and improves quality over time.</p>\n<ul>\n<li><strong>Template your registration pages.</strong> Build one optimized page template with all compliance elements (CME accreditation, disclosure, NPI capture). Clone it for each event, changing only the event-specific details. Our recurring event pricing reflects this: ${PRICING["event_first"]["low"]:,}-${PRICING["event_first"]["high"]:,} for the first event, ${PRICING["event_clone"]["low"]:,}-${PRICING["event_clone"]["high"]:,} per clone.</li>\n<li><strong>Standardize your compliance checklist.</strong> Build a pre-launch checklist covering all regulatory requirements. Run it before every event page goes live.</li>\n<li><strong>Build a physician engagement database.</strong> Track every physician interaction across events. Know who attended what, when, and what follow-up happened. This longitudinal view is more valuable than any single-event metric.</li>\n<li><strong>Measure consistently.</strong> Use the same metrics for every event so you can compare performance over time. Track cost per attendee, show-up rate, and attributed revenue using the same methodology every time.</li>\n</ul>\n<p>Medical device event marketing done well is one of the highest-ROI marketing investments in healthcare. Done poorly, it is an expensive dinner. The difference is in the systems: registration page optimization, compliance rigor, and disciplined measurement. <a href="/event-registration/">See our event registration service</a> for medical device companies.</p>',
                },
            ],
            "faqs": [
                {"question": "What is a CME dinner event?", "answer": "A CME (Continuing Medical Education) dinner is an educational event for physicians, typically held at a restaurant, where a Key Opinion Leader presents clinical data or techniques. Physicians earn CME credits for attending. Medical device companies often sponsor these events to educate physicians about their products in a compliant, accredited format."},
                {"question": "Do I need NPI numbers on my registration form?", "answer": "For events involving transfers of value to physicians (meals, gifts, travel), collecting NPI numbers at registration simplifies Sunshine Act (Open Payments) reporting. It is not legally required on the form itself, but collecting it at registration saves significant compliance effort compared to gathering it after the event."},
                {"question": "How much does a CME dinner cost?", "answer": "Total costs vary by city and venue but typically range from $5,000-$15,000 including venue, catering, KOL honorarium, accreditation fees, and marketing. Major cities (NYC, LA, Chicago) are at the high end. Adding the registration page and ad spend typically adds $3,000-$6,000."},
                {"question": "What show-up rate should I expect for physician events?", "answer": "CME dinners with rep-driven invitations see 70-85% show-up rates. Events promoted primarily through digital channels see 50-65%. Reminder sequences improve these numbers by 10-15%. Physicians who register through their rep are more committed than those who register through an ad."},
                {"question": "Can I use Facebook ads to reach physicians?", "answer": "Yes. Facebook and Instagram allow targeting by job title, employer, and education level. For physicians, target by job title (Surgeon, Physician, Cardiologist) and employer (major hospital systems in the event geography). Cost per registration for CME dinners is typically $20-$60 from paid social."},
            ],
        },
        {
            "slug": "conference-registration-website-guide",
            "title": "Conference Registration Website Design Guide",
            "description": "How to design a conference registration website that sells tickets. Covers information architecture, pricing tiers, speaker pages, agenda design, and mobile optimization.",
            "h1": "Conference Registration Website Design Guide",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "A Conference Website Is a Sales Page",
                    "content": '<p>A conference registration website has one job: sell tickets (or collect registrations for free events). Every design decision should be evaluated against that goal. Not "does it look impressive?" but "does it make someone more likely to register?"</p>\n<p>Conference websites that underperform usually fail for one of three reasons: important information is hard to find, the registration flow has too many steps, or the page loads too slowly on mobile. This guide covers the design decisions that affect conversion, organized by page section.</p>',
                },
                {
                    "heading": "Homepage: The Decision Architecture",
                    "content": '<p>Your conference homepage needs to answer five questions within 10 seconds of a visitor landing. If it does not, they leave. The five questions:</p>\n<ol>\n<li><strong>What is this event?</strong> Conference name and one-line description.</li>\n<li><strong>When?</strong> Date(s) prominently displayed. Not buried in a paragraph.</li>\n<li><strong>Where?</strong> City and venue. For virtual: "Online" with timezone.</li>\n<li><strong>How much?</strong> Starting price visible above the fold. "From $299" is fine. Hiding the price until the registration page is a conversion killer.</li>\n<li><strong>Why should I care?</strong> A single sentence about what makes this conference worth attending. Not your mission statement. A concrete value proposition.</li>\n</ol>\n<p>Place these five elements in the hero section. No hero video. No animated transitions. No stock photos. Just the information visitors need to decide whether to keep reading.</p>\n<p>Below the hero, the homepage should follow this order:</p>\n<ul>\n<li>Keynote speakers (the biggest draw)</li>\n<li>Agenda overview or track descriptions</li>\n<li>Social proof (past attendee stats, testimonials, company logos)</li>\n<li>Pricing tiers</li>\n<li>FAQ</li>\n<li>CTA repeated at bottom</li>\n</ul>',
                },
                {
                    "heading": "Pricing Tiers: Structure That Sells",
                    "content": '<p>Most conferences offer 2-4 pricing tiers. The structure of these tiers affects both total revenue and conversion rate.</p>\n<h3>The Three-Tier Standard</h3>\n<ul>\n<li><strong>Basic/Conference Only:</strong> Access to main sessions. No workshops, no VIP events. This is your entry price point.</li>\n<li><strong>Standard/Full Access:</strong> Conference sessions plus workshops. This should be your most popular tier. Price it 30-50% above Basic.</li>\n<li><strong>VIP/All Access:</strong> Everything plus exclusive events (speaker dinner, executive roundtable, front-row seating). Price it 2-3x Basic.</li>\n</ul>\n<h3>Design Principles for the Pricing Table</h3>\n<ul>\n<li><strong>Highlight the middle tier.</strong> Use a visual emphasis (border, background color, "Most Popular" badge) on the tier you want most people to buy. This is usually the Standard tier.</li>\n<li><strong>List features, not descriptions.</strong> "20+ sessions" is scannable. "Access to our comprehensive session lineup featuring thought leaders from across the industry" is not.</li>\n<li><strong>Show the per-day price for multi-day events.</strong> "$599 for 3 days" feels expensive. "$199/day" feels reasonable. Include both numbers.</li>\n<li><strong>Early bird pricing with a real deadline.</strong> Show the regular price crossed out next to the early bird price. Include the exact cutoff date. When the deadline passes, update the page. Fake deadlines destroy trust.</li>\n</ul>',
                },
                {
                    "heading": "Speaker Pages: The Primary Conversion Driver",
                    "content": '<p>For speaker-driven conferences, the speaker page is the highest-traffic page after the homepage. Design it to sell tickets, not just list names.</p>\n<h3>Speaker Grid (Index Page)</h3>\n<ul>\n<li>Professional headshots, all same dimensions (square or 3:4 ratio)</li>\n<li>Name, title, and company visible without clicking</li>\n<li>Compress headshots to 20-30KB each. 12 headshots at 200KB each means 2.4MB of image data on one page. At 25KB each, it is 300KB.</li>\n<li>Lazy-load all speaker images below the first row</li>\n<li>Link each speaker to their individual bio page or expand a modal with session details</li>\n</ul>\n<h3>Individual Speaker Pages</h3>\n<p>Each speaker should have a dedicated page (or expandable section) with:</p>\n<ul>\n<li>Full bio (3-5 sentences)</li>\n<li>Session title and description</li>\n<li>Session date and time slot</li>\n<li>CTA: "Register to see [Speaker Name]" linking directly to the registration form</li>\n</ul>\n<p>The individual speaker page CTA is important. Visitors often arrive at speaker pages via social media shares or direct links. They need a direct path to registration from that page without going through the homepage first.</p>',
                },
                {
                    "heading": "Agenda Design: Scannable, Not Overwhelming",
                    "content": '<p>Conference agendas can be complex, especially for multi-track, multi-day events. The design challenge is making them scannable without losing necessary detail.</p>\n<h3>Single-Track Events</h3>\n<p>Use a simple timeline layout:</p>\n<ul>\n<li>Time in left column</li>\n<li>Session title and speaker in right column</li>\n<li>Expandable descriptions for each session (click to expand, not visible by default)</li>\n<li>Visual distinction between session types (keynote, breakout, networking, meal)</li>\n</ul>\n<h3>Multi-Track Events</h3>\n<p>Multi-track agendas are harder. Two approaches that work:</p>\n<ul>\n<li><strong>Tab-based:</strong> Tabs for each track. One track visible at a time. Works for 2-4 tracks. Beyond 4, the tabs become hard to navigate on mobile.</li>\n<li><strong>Filter-based:</strong> Show all sessions with filter buttons for track, day, and session type. Better for 5+ tracks or when attendees want to see sessions across tracks.</li>\n</ul>\n<p>Avoid the grid layout (tracks as columns, time slots as rows) on conference websites. It looks organized on desktop but is unusable on mobile. Since 50%+ of traffic is mobile, the grid layout fails for half your audience.</p>\n<h3>Day-Based Navigation</h3>\n<p>For multi-day conferences, add day tabs at the top of the agenda. Default to Day 1. Each day should load quickly without a full page reload (use JavaScript tabs or sections, not separate pages).</p>',
                },
                {
                    "heading": "Registration Flow: Every Step Costs You Registrants",
                    "content": '<p>The registration flow is where conference websites lose the most potential attendees. Every additional step between "I want to register" and "I am registered" costs 10-20% of remaining visitors.</p>\n<h3>Optimal Flow (3 Steps or Fewer)</h3>\n<ol>\n<li>Click "Register" button</li>\n<li>Select tier and fill in personal details (one page)</li>\n<li>Payment (ideally embedded on the same page, not a redirect)</li>\n</ol>\n<h3>What to Avoid</h3>\n<ul>\n<li><strong>Account creation before registration.</strong> Do not make people create an account to register. Capture their email during registration and let them create an account (for session selection, networking features) after they have paid.</li>\n<li><strong>Session selection during registration.</strong> Let people register first, select sessions later. Forcing session selection during checkout adds complexity and decision fatigue. Send a follow-up email with session selection after registration.</li>\n<li><strong>Redirects to third-party platforms.</strong> Every redirect is a drop-off point. If you use a third-party registration tool, embed it via iframe or API integration rather than linking out.</li>\n</ul>',
                },
                {
                    "heading": "Mobile Design: Not an Afterthought",
                    "content": f'<p>50-65% of conference website traffic comes from mobile devices. The percentage is highest for traffic from social media promotion and email campaigns (which are read on phones).</p>\n<h3>Mobile-Critical Elements</h3>\n<ul>\n<li><strong>Sticky CTA button.</strong> A fixed "Register" button at the bottom of the mobile viewport. Always visible, always tappable. This single element can improve mobile conversion by 10-15%.</li>\n<li><strong>Single-column agenda.</strong> Do not try to show multi-track grids on mobile. Use day tabs and track filters with a single-column layout.</li>\n<li><strong>Collapsible sections.</strong> Session descriptions, speaker bios, and FAQ answers should be collapsed by default on mobile. Show headings and let users expand what interests them.</li>\n<li><strong>Fast load time.</strong> Conference websites with large speaker image grids often load in 5-8 seconds on mobile. Target under 2 seconds by compressing all images, lazy-loading below the fold, and minimizing JavaScript.</li>\n</ul>\n<h3>What Breaks on Mobile</h3>\n<ul>\n<li>Pricing comparison tables (columns get too narrow to read)</li>\n<li>Embedded maps (often load slowly and are hard to interact with on small screens)</li>\n<li>PDF agendas (require download, pinch-zoom, terrible experience)</li>\n<li>Form fields with tiny tap targets</li>\n</ul>\n<p>Test every page on a real phone before launch. If you cannot register from start to finish on a phone in under 2 minutes, something needs to change.</p>\n<p>Our conference sites are built mobile-first with sub-second load times. Static HTML, no platform bloat. <a href="/event-registration/">See our event registration service</a> or <a href="/audit/">run a free audit</a> on your current conference site.</p>',
                },
            ],
            "faqs": [
                {"question": "How many pages should a conference website have?", "answer": "At minimum: homepage (with hero, speakers, agenda overview, pricing), speakers page, full agenda page, registration/checkout page, and FAQ. Larger conferences add: individual speaker pages, sponsor page, venue/travel page, and a blog or news section for pre-event content marketing."},
                {"question": "Should I use a conference platform or build a custom site?", "answer": f"Conference platforms (Cvent, Whova, Swoogo) offer built-in features like session selection, networking, and check-in apps. They are convenient but expensive and slow-loading. Custom static sites load faster, convert better, and cost less long-term. For events needing an attendee app, consider a hybrid: custom marketing site plus a lightweight event app. Custom conference sites start at ${PRICING['event_first']['low']:,}."},
                {"question": "How do I display a multi-track agenda on mobile?", "answer": "Do not use a grid layout on mobile. Use day tabs at the top and track filter buttons below. Show sessions in a single-column list, organized by time. Each session shows time, title, speaker, and track badge. Collapsible descriptions keep the view scannable. This approach works for any number of tracks."},
                {"question": "What is the most important design element for conference ticket sales?", "answer": "The pricing table. It should be visible without excessive scrolling, highlight the recommended tier, show early bird vs. regular pricing, and have a clear CTA button for each tier. After the pricing table, speaker quality and agenda clarity are the strongest conversion drivers."},
                {"question": "How fast should a conference website load?", "answer": "Under 2 seconds on mobile. Conference sites commonly load in 5-8 seconds due to large speaker image grids and platform overhead. Compress speaker headshots to 20-30KB each, lazy-load images below the first row, and minimize JavaScript. Fast sites convert 15-25% better than slow ones."},
            ],
        },
        {
            "slug": "facebook-retargeting-for-events",
            "title": "Facebook Retargeting for Events: Pixel and Audience Setup",
            "description": "Complete guide to Facebook retargeting for event promotion. Covers pixel setup, custom audience creation, ad creative for retargeting, and budget allocation.",
            "h1": "Facebook Retargeting for Events: Pixel and Audience Setup",
            "author": "Rome Thorndike",
            "sections": [
                {
                    "heading": "Why Retargeting Is the Highest-ROI Event Ad Strategy",
                    "content": '<p>Most event promotion budgets go to cold audiences: people who have never heard of your event. Cold traffic converts at 1-5% for event registration pages. Retargeting traffic (people who already visited your registration page but did not register) converts at 10-25%.</p>\n<p>The math is simple. If you spend $500 reaching cold audiences at $5 per click and 3% conversion, you get 3 registrations. If you spend $200 retargeting your 167 non-registrants at $1 per click and 15% conversion, you get 25 registrations. The retargeting budget is smaller and produces 8x the registrations.</p>\n<p>The catch: retargeting only works if you have the pixel infrastructure set up before you start driving traffic. Visitors who land on your page without pixel tracking are invisible to your retargeting campaigns. This guide walks through the complete setup.</p>',
                },
                {
                    "heading": "Step 1: Install the Facebook Pixel",
                    "content": '<p>The Facebook (Meta) Pixel is a snippet of JavaScript that fires on your event registration page. It tells Facebook who visited, what they did, and whether they registered.</p>\n<h3>Base Pixel Installation</h3>\n<p>Place the base pixel code in the <code>&lt;head&gt;</code> of every page on your event site. This fires the <code>PageView</code> event automatically, which tells Facebook someone landed on your page.</p>\n<pre><code>&lt;!-- Meta Pixel Code --&gt;\n&lt;script&gt;\n!function(f,b,e,v,n,t,s)\n{if(f.fbq)return;n=f.fbq=function(){n.callMethod?\nn.callMethod.apply(n,arguments):n.queue.push(arguments)};\nif(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version=\'2.0\';\nn.queue=[];t=b.createElement(e);t.async=!0;\nt.src=v;s=b.getElementsByTagName(e)[0];\ns.parentNode.insertBefore(t,s)}(window, document,\'script\',\n\'https://connect.facebook.net/en_US/fbevents.js\');\nfbq(\'init\', \'YOUR_PIXEL_ID\');\nfbq(\'track\', \'PageView\');\n&lt;/script&gt;</code></pre>\n<p>Replace <code>YOUR_PIXEL_ID</code> with your actual pixel ID from Meta Events Manager.</p>\n<h3>Important: One Pixel Per Event (or Per Client)</h3>\n<p>If you run multiple events for different purposes, use separate pixels or at minimum separate custom conversions. Mixing event data from a medical conference and a local meetup in the same pixel creates noisy audiences that hurt optimization.</p>',
                },
                {
                    "heading": "Step 2: Set Up Custom Events",
                    "content": '<p>The base pixel tracks page visits. Custom events track specific actions that indicate intent and completion.</p>\n<h3>ViewContent Event (Qualified Visitor)</h3>\n<p>Fire a <code>ViewContent</code> event when a visitor has been on the page for 10 seconds. This filters out bounces and identifies people who actually read the page.</p>\n<pre><code>// Fire ViewContent after 10 seconds on page\nsetTimeout(function() {\n  fbq(\'track\', \'ViewContent\', {\n    content_name: \'Event Registration Page\',\n    content_category: \'Event\'\n  });\n}, 10000);</code></pre>\n<p>This 10-second threshold is critical. Facebook optimizes ad delivery based on the events you tell it to optimize for. If you optimize for PageView, Facebook sends anyone who will click (including bots and accidental clicks). If you optimize for ViewContent with a 10-second threshold, Facebook sends people who actually engage with the page.</p>\n<h3>CompleteRegistration Event</h3>\n<p>Fire <code>CompleteRegistration</code> when the registration form is successfully submitted. This is your conversion event.</p>\n<pre><code>// Fire on successful form submission\nfunction onRegistrationComplete() {\n  fbq(\'track\', \'CompleteRegistration\', {\n    content_name: \'Event Name\',\n    value: 0.00,  // ticket price, 0 for free events\n    currency: \'USD\'\n  });\n}\n\n// Attach to your form\'s success handler\ndocument.getElementById(\'reg-form\').addEventListener(\'submit\', function(e) {\n  // After form validation passes:\n  onRegistrationComplete();\n});</code></pre>\n<h3>InitiateCheckout Event (Paid Events)</h3>\n<p>For paid events, fire <code>InitiateCheckout</code> when a visitor clicks to start the payment process but before they complete payment. This creates a middle-funnel audience: people who wanted to pay but did not finish.</p>\n<pre><code>// Fire when user clicks "Proceed to Payment"\ndocument.getElementById(\'checkout-btn\').addEventListener(\'click\', function() {\n  fbq(\'track\', \'InitiateCheckout\', {\n    content_name: \'Event Name\',\n    value: 99.00,\n    currency: \'USD\'\n  });\n});</code></pre>',
                },
                {
                    "heading": "Step 3: Build Custom Audiences",
                    "content": '<p>With the pixel firing events, build these custom audiences in Meta Ads Manager:</p>\n<h3>Audience 1: All Page Visitors (Exclude Registrants)</h3>\n<p>Go to Audiences > Create Audience > Custom Audience > Website > People who visited specific web pages.</p>\n<ul>\n<li>URL contains: your event registration page URL</li>\n<li>Exclude: people who triggered CompleteRegistration</li>\n<li>Time window: 30 days (adjust based on your promotion timeline)</li>\n</ul>\n<p>This is your primary retargeting audience. Everyone who visited but did not register.</p>\n<h3>Audience 2: Engaged Visitors (Exclude Registrants)</h3>\n<ul>\n<li>People who triggered ViewContent (10-second visitors)</li>\n<li>Exclude: people who triggered CompleteRegistration</li>\n<li>Time window: 14 days</li>\n</ul>\n<p>This is a higher-intent audience. These people read your page but did not convert. They are your best retargeting targets.</p>\n<h3>Audience 3: Checkout Abandoners (Paid Events Only)</h3>\n<ul>\n<li>People who triggered InitiateCheckout</li>\n<li>Exclude: people who triggered CompleteRegistration</li>\n<li>Time window: 7 days</li>\n</ul>\n<p>The highest-intent audience. These people wanted to register enough to start paying but stopped. A reminder ad often recovers 20-30% of checkout abandoners.</p>\n<h3>Audience 4: Registrants (For Upsell or Future Events)</h3>\n<ul>\n<li>People who triggered CompleteRegistration</li>\n<li>Time window: 180 days</li>\n</ul>\n<p>Use this audience to promote ticket upgrades (basic to VIP), add-on workshops, or future events in the series. Do not show these people registration ads. They already registered.</p>',
                },
                {
                    "heading": "Step 4: Create Retargeting Ad Campaigns",
                    "content": '<p>Retargeting ads should be different from your cold-audience ads. The audience already knows about your event. They do not need an introduction. They need a reason to act now.</p>\n<h3>Ad Creative for Retargeting</h3>\n<ul>\n<li><strong>Urgency-based:</strong> "Only 15 spots left for [Event Name]. Register before [date]." Use real scarcity if it exists.</li>\n<li><strong>Social proof:</strong> "200 professionals already registered for [Event Name]. Join them." Use actual numbers.</li>\n<li><strong>Objection-handling:</strong> If people visit but do not register, they have an objection. Common objections for events: "Is it worth the time/money?" Address it directly: "Last year\'s attendees rated us 4.8/5. Here\'s what they said."</li>\n<li><strong>New information:</strong> Announce a new speaker, a new session, or a new perk. Give people a reason to revisit the page.</li>\n</ul>\n<h3>Campaign Structure</h3>\n<ul>\n<li><strong>Campaign 1: Page Visitors (Audience 1)</strong> - Broad retargeting. Budget: 30-40% of retargeting spend. Optimize for CompleteRegistration or ViewContent.</li>\n<li><strong>Campaign 2: Engaged Visitors (Audience 2)</strong> - High-intent retargeting. Budget: 40-50% of retargeting spend. Optimize for CompleteRegistration.</li>\n<li><strong>Campaign 3: Checkout Abandoners (Audience 3)</strong> - Recovery campaign. Budget: 10-20% of retargeting spend. Optimize for CompleteRegistration. Use urgency-based creative.</li>\n</ul>\n<h3>Budget Allocation</h3>\n<p>Allocate 20-30% of your total ad budget to retargeting. For example, on a $2,000 event ad budget: $1,400-$1,600 to cold audience campaigns driving traffic to the registration page, $400-$600 to retargeting campaigns converting that traffic.</p>\n<p>The retargeting portion will produce a disproportionate share of registrations relative to spend. That is the point.</p>',
                },
                {
                    "heading": "Step 5: Optimize for the Right Event",
                    "content": '<p>Campaign optimization settings determine which people Facebook shows your ads to. This is where many event promoters go wrong.</p>\n<h3>What to Optimize For</h3>\n<ul>\n<li><strong>Cold campaigns:</strong> Optimize for Link Clicks or ViewContent (10-second event). Do NOT optimize for Landing Page Views. LPV optimization sends cheap, low-quality traffic with high bounce rates. ViewContent ensures Facebook finds people who actually engage with your page.</li>\n<li><strong>Retargeting campaigns:</strong> Optimize for CompleteRegistration if you have enough conversion volume (at least 15-25 conversions per week). If volume is too low, optimize for ViewContent and let the audience targeting do the work.</li>\n</ul>\n<h3>What NOT to Optimize For</h3>\n<ul>\n<li><strong>Landing Page Views.</strong> Facebook defines an LPV as "clicked the link and the page started loading." This includes people who clicked accidentally, clicked and immediately bounced, or had the page load in the background. LPV optimization is cheap but produces junk traffic with 80-97% bounce rates.</li>\n<li><strong>Impressions or Reach.</strong> Unless you are running pure brand awareness (rare for event promotion), optimizing for impressions wastes budget on people who will never register.</li>\n</ul>',
                },
                {
                    "heading": "Troubleshooting and Common Mistakes",
                    "content": '<ul>\n<li><strong>Pixel not firing.</strong> Use the Meta Pixel Helper Chrome extension to verify your pixel fires on every page load. Check that events (ViewContent, CompleteRegistration) fire at the right times. Test in an incognito window to avoid browser extensions blocking the pixel.</li>\n<li><strong>Audiences too small.</strong> Retargeting requires enough page visitors to build a viable audience. Facebook needs at least 100 people in an audience to serve ads. If your event page does not get enough traffic, combine Audiences 1 and 2 into a single audience, or extend the time window.</li>\n<li><strong>Showing retargeting ads to registrants.</strong> Always exclude your CompleteRegistration audience from retargeting campaigns. Showing "Register now!" to someone who already registered is wasteful and annoying.</li>\n<li><strong>Using the same creative for cold and retargeting.</strong> People who already visited your page have seen your event pitch. Showing them the same ad again is a wasted impression. Retargeting creative should add new information, urgency, or social proof.</li>\n<li><strong>Setting retargeting budget too high relative to cold traffic.</strong> Retargeting only works if you have enough visitors to retarget. If your retargeting audience is 200 people and you allocate $500/week to reach them, frequency will spike and performance will drop. Match retargeting budget to audience size: roughly $1-$3 per person in the audience per week.</li>\n<li><strong>Sharing pixels across unrelated events.</strong> Each event (or at minimum, each event type) should have its own pixel or custom conversion events. Mixing data from a 500-person conference and a 30-person dinner in the same optimization signals confuses Facebook\'s algorithm.</li>\n</ul>',
                },
                {
                    "heading": "The Full Timeline for Event Retargeting",
                    "content": f'<p>Here is a typical timeline for event retargeting from setup to event day:</p>\n<h3>4-6 Weeks Before Event</h3>\n<ul>\n<li>Install pixel on registration page</li>\n<li>Set up custom events (ViewContent, CompleteRegistration)</li>\n<li>Verify pixel firing with Meta Pixel Helper</li>\n<li>Launch cold traffic campaigns to drive page visitors</li>\n</ul>\n<h3>3-4 Weeks Before Event</h3>\n<ul>\n<li>Build custom audiences from accumulated visitor data</li>\n<li>Launch retargeting Campaign 1 (All Visitors) and Campaign 2 (Engaged Visitors)</li>\n<li>Monitor frequency. If retargeting frequency exceeds 3-4 impressions per person per week, reduce budget or refresh creative.</li>\n</ul>\n<h3>2 Weeks Before Event</h3>\n<ul>\n<li>Launch Campaign 3 (Checkout Abandoners) if applicable</li>\n<li>Shift budget from cold to retargeting as audiences grow</li>\n<li>Update retargeting creative with urgency messaging ("2 weeks left to register")</li>\n</ul>\n<h3>Final Week</h3>\n<ul>\n<li>Increase retargeting budget for final push</li>\n<li>Use strongest urgency creative ("Last chance: event is [date]")</li>\n<li>Pause cold campaigns if budget is limited (retargeting converts at higher rate)</li>\n</ul>\n<h3>Event Day</h3>\n<ul>\n<li>Pause all registration campaigns</li>\n<li>Switch registrant audience (Audience 4) to future event promotion or thank-you messaging</li>\n</ul>\n<p>This setup requires a custom registration page with pixel control. Eventbrite limits pixel placement and custom events, which makes the full retargeting strategy impossible to execute. If you are spending money on ads to fill an event, the pixel setup alone justifies the cost of a custom page. <a href="/event-registration/">See our event registration service</a> for pages built with full pixel infrastructure from day one.</p>',
                },
            ],
            "faqs": [
                {"question": "What is Facebook retargeting for events?", "answer": "Facebook retargeting shows ads to people who visited your event registration page but did not register. It works by placing a tracking pixel on your page that identifies visitors, then creating custom audiences in Facebook Ads Manager to serve them follow-up ads. Retargeting traffic converts at 10-25%, compared to 1-5% for cold traffic."},
                {"question": "How much should I spend on retargeting vs. cold traffic?", "answer": "Allocate 20-30% of your total ad budget to retargeting. The remaining 70-80% drives cold traffic to your registration page. Retargeting produces a disproportionate share of registrations relative to spend, but it needs cold traffic to build the audience first."},
                {"question": "Can I retarget Eventbrite page visitors?", "answer": "Eventbrite allows basic pixel placement, but you cannot fire custom events (like timed ViewContent) or build the full audience segmentation described in this guide. For complete retargeting capability, you need a custom registration page where you control pixel placement."},
                {"question": "What should Facebook retargeting ads say?", "answer": "Do not repeat your original ad. Retargeting creative should add new information (new speaker announced), create urgency (registration closing soon), provide social proof (X people already registered), or address objections (what past attendees said about the event). The audience already knows about your event. Give them a reason to act now."},
                {"question": "How many people do I need in my retargeting audience?", "answer": "Facebook requires at least 100 people in a custom audience to serve ads. For effective retargeting, aim for 500+ visitors before launching retargeting campaigns. At typical click-through rates, this means spending $500-$1,500 on cold traffic first to build the audience pool."},
            ],
        },
    ]
