"""ICP page data for SharpPages v2. This file is read by _splice_icp.py."""


def get_icp_pages(PRICING):
    """Return the ICP_PAGES list with pricing references resolved."""
    return [
        {
            "slug": "medical-device-companies",
            "name": "Medical Device Companies",
            "title": "Web Design and SEO for Medical Device Companies",
            "description": "Fast websites and SEO for medical device companies. Event registration sites, programmatic SEO, ad campaigns. 90+ PageSpeed scores, flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Medical Device Companies</span>',
            "intro": "Medical device companies run field marketing events, maintain product websites, and need to rank for clinical search terms. Most are stuck with agency-built WordPress sites that score 60 on mobile PageSpeed and cost $5,000 per year in hosting and maintenance.",
            "pain_points": [
                "Your corporate site loads in 4 seconds on mobile. Physicians evaluating your products on their phones between patients close the tab before the page renders.",
                "Compliance review cycles add weeks to every agency deliverable. By the time the landing page is approved, you have lost half the promotion window.",
                "You run 10 to 20 field events per year across multiple cities. Each one needs a registration page, tracking, and an ad campaign. Starting from scratch every time compounds the overhead.",
            ],
            "workflow": [
                "We audit your current site and identify performance bottlenecks, SEO gaps, and conversion opportunities.",
                "We build a fast, compliant site on your domain. Static HTML, 90+ PageSpeed score, full schema markup. Your compliance team reviews copy before anything goes live.",
                "For event registration, we build custom pages with GA4 and Meta Pixel. Template cloning for multi-city rollouts takes 48 hours per city.",
                "If you need SEO, we build programmatic pages targeting clinical search terms, product comparisons, and specialty-specific content.",
                "Ad campaigns run on Facebook and Instagram with custom audience targeting from your physician contact databases. Full attribution from impression to registration.",
                "You own all files. No CMS to maintain, no plugins to update, no recurring platform fees.",
            ],
            "pricing_context": f"Website builds start at ${PRICING['site_standard']['low']:,}. Event registration sites: ${PRICING['event_first']['low']:,} to ${PRICING['event_first']['high']:,}. SEO buildouts: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Ad management: ${PRICING['ad_monthly']['low']:,} to ${PRICING['ad_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "Can you work within pharma/device compliance requirements?", "answer": "Yes. You send approved copy, or we draft copy for your compliance team to review. The build does not go live until your team signs off. We are used to revision cycles."},
                {"question": "Do you build on WordPress?", "answer": "No. Static HTML sites load faster, score higher on PageSpeed, and have zero plugin vulnerabilities. No CMS maintenance. Your site files live in a repository you control."},
                {"question": "Can you handle multi-city event rollouts?", "answer": "Yes. We build the first event site as a template. Each additional city clones in 48 hours with local venue, date, and contact list details swapped in. Same design, separate tracking per city."},
                {"question": "What PageSpeed scores do your sites achieve?", "answer": "90+ on mobile, consistently. Our benchmark site (getprovyx.com) scores 98 with a 0.9s Speed Index across 398 pages. Run it through PageSpeed Insights yourself."},
            ],
            "deep_dive": [
                "Medical device marketing has a credibility problem online. Your products go through years of clinical trials and FDA clearance, but your website looks like it was built on a Squarespace template in 2019. Physicians evaluating your products form an impression of your company before they ever speak to a rep. A slow, dated site undermines the clinical credibility your products earned.",
                "Field marketing events are the backbone of device sales. Physician dinners, KOL presentations, product demos, city-by-city lunch-and-learns. Each event needs a registration page that communicates the same quality as the event itself. Generic Eventbrite pages with default styling do not meet that standard for a premium physician dinner at a five-star hotel.",
                "The template cloning model is built for how device companies operate. You run the same event format in Minneapolis, then Detroit, then Dallas. Each city gets a fresh site with local details, but the design, tracking architecture, and proven copy structure carry over. By the fourth city, your cost per event site drops to a fraction of the first.",
                "SEO for medical devices targets specific clinical terms, product comparisons, and specialty-focused content. Programmatic SEO generates hundreds of pages from structured data, each targeting a specific search intent. The same approach that drove 363K impressions in 30 days for PE Collective works for device companies targeting surgical specialties, orthopedics, or dermatology.",
            ],
            "outbound_links": [
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
                {"text": "Google Search Console", "url": "https://search.google.com/search-console/about"},
            ],
        },
        {
            "slug": "pharma-field-marketing",
            "name": "Pharma Field Marketing",
            "title": "Websites and SEO for Pharma Field Marketing Teams",
            "description": "Fast websites, event registration sites, and SEO for pharma field marketing. Compliance-friendly builds. 90+ PageSpeed scores, flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Pharma Field Marketing</span>',
            "intro": "Speaker programs, advisory boards, regional symposia, HCP engagement dinners. Pharma field marketing teams run events where the digital experience has to match the clinical credibility of the brand. Most agency-built sites fall short on speed, compliance workflow, and tracking.",
            "pain_points": [
                "Your agency takes 4 to 6 weeks for an event page. By the time it clears medical/legal/regulatory review, you have lost half your promotion window.",
                "Internal teams are stretched across product launches, congress prep, and quarterly campaigns. A regional dinner event does not get priority until it is an emergency.",
                "Your corporate site scores 55 on mobile PageSpeed. HCPs evaluating your programs on their phones see a slow, bloated experience that does not reflect the quality of your science.",
            ],
            "workflow": [
                "We audit your current web presence: PageSpeed scores, SEO gaps, event registration workflow, and tracking setup.",
                "For corporate/product sites, we build static HTML that loads in under a second. Your compliance team reviews all copy before launch.",
                "For events, we build branded registration pages with GA4 and Meta Pixel. Each event gets its own tracking dataset.",
                "We build custom audiences from HCP contact data and run targeted ad campaigns on Facebook and Instagram.",
                "Template cloning for multi-market rollouts: same design, fresh local details, 48-hour turnaround per city.",
                "Post-campaign reporting with full attribution from ad impression to registration.",
            ],
            "pricing_context": f"Website builds: ${PRICING['site_standard']['low']:,} to ${PRICING['site_standard']['high']:,}. Event sites: ${PRICING['event_first']['low']:,} to ${PRICING['event_first']['high']:,}. Ad management: ${PRICING['ad_monthly']['low']:,} to ${PRICING['ad_monthly']['high']:,}/mo. All flat fee.",
            "faqs": [
                {"question": "Do you have experience with pharma compliance review cycles?", "answer": "Yes. We draft copy for your MLR team to review, or build from your approved copy. The site does not go live until your compliance team signs off. We are used to multiple revision rounds."},
                {"question": "Can you handle NPI-matched targeting for ads?", "answer": "If your contact list includes NPI numbers alongside email and phone, we can segment audiences by specialty and target specific physician populations."},
                {"question": "How do you handle CME/CE credit details on event pages?", "answer": "We include accreditation statements, learning objectives, speaker bios, and CME/CE credit details on the registration page. Your medical education team provides the content; we handle the presentation."},
                {"question": "What happens to event sites after the program?", "answer": "You own the files. We can archive the site, redirect it to your corporate domain, or update it for the next event in the same market."},
            ],
            "deep_dive": [
                "Pharma field marketing operates under constraints most web agencies have never encountered. Medical/legal/regulatory review adds days to every deliverable. Copy that mentions efficacy data or clinical outcomes triggers a review chain that stalls projects for weeks if the agency is not prepared.",
                "The registration page is often the first digital touchpoint between your field team and the HCP audience. It needs to reflect the same professionalism your MSLs bring to one-on-one meetings. A generic event platform with default fonts and stock headers does not meet that standard.",
                "Speed matters for pharma sites because HCPs are time-constrained. A physician scrolling Facebook between patients will give your ad exactly one tap. If the registration page takes 4 seconds to load, they are back in their feed before the page renders. Sub-1-second load times from static HTML keep them on the page long enough to register.",
                "The programmatic SEO model applies to pharma marketing sites that need to rank for therapeutic area terms, drug comparisons, and clinical resource searches. Hundreds of structured pages, each with proper schema markup, outperform a 20-page corporate site competing for the same keywords.",
            ],
            "outbound_links": [
                {"text": "Meta Ads Manager", "url": "https://www.facebook.com/business/tools/ads-manager"},
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
            ],
        },
        {
            "slug": "b2b-saas",
            "name": "B2B SaaS",
            "title": "Web Design and SEO for B2B SaaS Companies",
            "description": "Fast marketing sites, programmatic SEO, and ad campaigns for B2B SaaS. 90+ PageSpeed scores, hundreds of SEO pages, flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">B2B SaaS Companies</span>',
            "intro": "Your product is fast. Your marketing site should be too. Most B2B SaaS marketing sites are built on WordPress or Webflow, score 60 to 75 on mobile PageSpeed, and compete for keywords with a 15-page site against competitors with 500.",
            "pain_points": [
                "Your Webflow site looks good but scores 70 on mobile PageSpeed. Google cares about Core Web Vitals, and your competitors with faster sites are outranking you.",
                "You have 15 marketing pages competing against competitors with 300+. In programmatic SEO, volume wins when quality is held constant.",
                "Your marketing team is optimized for demand gen, not web development. Building a comparison page takes a designer, a developer, and a content writer. You ship 4 pages per month.",
            ],
            "workflow": [
                "We audit your site: PageSpeed scores, keyword gaps, content architecture, schema markup, and competitor page counts.",
                "We build or migrate your marketing site to static HTML. Same design (or improved), 90+ PageSpeed score, sub-1-second load times.",
                "We build programmatic SEO pages at scale: comparisons (you vs. competitor), alternatives pages, use case pages, integration pages, industry verticals.",
                "Each page gets unique content, schema markup, internal links, and targets a specific keyword cluster.",
                "For events (roadshows, user groups, partner summits), we build registration sites with tracking and ad campaigns.",
                "You own all files. Deploy on Netlify, Cloudflare Pages, GitHub Pages, or your own CDN.",
            ],
            "pricing_context": f"Marketing site build: ${PRICING['site_standard']['low']:,} to ${PRICING['site_content']['high']:,}. Programmatic SEO: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Monthly SEO: ${PRICING['seo_monthly']['low']:,} to ${PRICING['seo_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "Can you replicate our Webflow design in static HTML?", "answer": "Yes. We can match your current design pixel-for-pixel or improve it during migration. The output is static HTML/CSS/JS that scores 90+ on PageSpeed. Same look, 5x faster."},
                {"question": "What does programmatic SEO look like for SaaS?", "answer": "Comparison pages (you vs. each competitor), alternatives pages, use case pages, integration pages, and industry vertical pages. Each page targets a specific search query with unique content. We built 398 pages for one client using this model."},
                {"question": "Can you integrate with our existing CMS or blog?", "answer": "The static site can coexist with your existing blog on a subdomain. Or we can build the blog into the static site with Article schema and automated sitemap generation."},
                {"question": "How does this compare to hiring a content agency?", "answer": "Content agencies produce 4 to 8 blog posts per month. Programmatic SEO generates 100+ pages from structured data in a single build. Different approach, different scale."},
            ],
            "deep_dive": [
                "B2B SaaS SEO is a volume game. Your competitors are building comparison pages, alternatives pages, and use case pages at scale. If they have 300 pages targeting keywords and you have 15, they win regardless of domain authority. Programmatic SEO closes that gap by generating hundreds of structured pages from your product data, competitor data, and industry data.",
                "Page speed is a ranking factor and a conversion factor. Google confirmed Core Web Vitals as a ranking signal. A SaaS marketing site that loads in 4 seconds on mobile loses visitors and ranks lower than a site that loads in 0.9 seconds. Most Webflow and WordPress sites score 60 to 75 on mobile. Our static sites score 90+.",
                "The comparison page model is especially powerful for SaaS. Every potential customer searches '[your product] vs [competitor]' during evaluation. If your competitor owns that page, they control the narrative. If you own it, you frame the comparison on your terms with your data.",
                "Integration and use case pages work similarly. A page titled 'Best CRM for real estate agents' or '[Product] + Salesforce integration' targets search queries from prospects already evaluating solutions. Each page is a landing pad for a specific buyer intent.",
            ],
            "outbound_links": [
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
                {"text": "Google Search Console", "url": "https://search.google.com/search-console/about"},
            ],
        },
        {
            "slug": "conference-organizers",
            "name": "Conference Organizers",
            "title": "Websites and Registration Sites for Conference Organizers",
            "description": "Custom conference websites and registration pages. No per-registrant fees, no Cvent pricing. Speaker bios, sponsor tiers, agenda pages. 90+ PageSpeed.",
            "h1": 'Web Design for <span class="text-accent">Conference Organizers</span>',
            "intro": "You run a conference with 200+ attendees, sponsors, speakers, and breakout sessions. Cvent costs $15,000 to $50,000 per year. Eventbrite caps out at casual meetups. You need something in the middle that loads fast, looks professional, and costs a flat fee.",
            "pain_points": [
                "Cvent pricing is built for enterprises running 50+ events per year. If you run one annual conference or a small series, you are paying for features you will never touch.",
                "Eventbrite is affordable but limited. The URL says eventbrite.com, the layout is generic, and per-ticket fees add up fast for free or low-cost registration.",
                "Your current setup is stitched together: WordPress page nobody maintains, Google Form for registration, Mailchimp for confirmations, and no tracking connecting your ad spend to actual signups.",
            ],
            "workflow": [
                "We build a multi-section conference site on your domain: speaker bios, session descriptions, sponsor logos, venue details, and registration form.",
                "Every page scores 90+ on PageSpeed. Mobile-responsive, accessible, and fast on any device.",
                "GA4 and Meta Pixel track every registration as a conversion. You know which ad, email, or channel drove each signup.",
                "Sponsor logos tiered by package level (platinum, gold, silver). Agenda with session breakdowns.",
                "Ad campaigns target your mailing list, past attendees, and sponsor contact databases.",
                "After the conference, the site stays live as an archive or updates for next year. Template and tracking carry over.",
            ],
            "pricing_context": f"Conference site: ${PRICING['site_standard']['low']:,} to ${PRICING['site_content']['high']:,} depending on page count. Ad management: ${PRICING['ad_monthly']['low']:,} to ${PRICING['ad_monthly']['high']:,}/mo. No per-registrant fees.",
            "faqs": [
                {"question": "Can you handle tiered registration pricing?", "answer": "Yes. Early bird, general admission, VIP, speaker, and sponsor tiers. For payment processing, we integrate with Stripe or your preferred provider."},
                {"question": "How do sponsors get visibility on the site?", "answer": "Dedicated sponsor sections tiered by package level. Platinum sponsors get logo, description, and link. Gold and silver get scaled visibility matching your sponsorship packages."},
                {"question": "Can attendees select sessions during registration?", "answer": "We can add session selection, track preferences, dietary requirements, and accessibility needs to the registration form."},
                {"question": "What about email confirmations?", "answer": "The form triggers automatic confirmation through Formspree or your email system. For reminder sequences, we connect to your email platform."},
            ],
            "deep_dive": [
                "Conference websites sit in an awkward gap between enterprise event platforms and simple registration tools. Cvent and Bizzabo are built for dedicated event ops teams managing 50+ events per year. The features are powerful but the pricing assumes enterprise budgets. If you run one annual conference, the math does not work.",
                "A custom conference site gives you full branding control, unlimited pages, proper tracking, and no per-registrant fees. Speaker bios, session descriptions, sponsor logos tiered by package, venue details with maps, and early bird pricing with countdowns. All on your domain, loading in under a second.",
                "For recurring conferences, the template model saves weeks each year. Update speakers, sessions, sponsors, and dates. The design, tracking, and proven page structure carry over. Your team spends time on programming and promotion instead of rebuilding registration infrastructure.",
                "Sponsor visibility matters. Platinum sponsors paid $10,000 or more. They expect prominent placement, not a small logo in the footer. A custom site gives each tier the visual prominence the sponsorship package promises.",
            ],
            "outbound_links": [
                {"text": "Google Analytics 4", "url": "https://analytics.google.com/"},
                {"text": "Formspree", "url": "https://formspree.io/"},
            ],
        },
        {
            "slug": "med-spas",
            "name": "Med Spas",
            "title": "Web Design and SEO for Med Spas",
            "description": "Fast, premium websites and local SEO for med spas. Patient acquisition, Google rankings, 90+ PageSpeed scores, flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Med Spas</span>',
            "intro": "Your med spa sells premium aesthetics. Your website should reflect that. Most med spa sites load in 3 to 5 seconds on mobile and compete for local search terms with a handful of pages. Patients searching 'Botox near me' find your competitor because their site loads faster and has more content.",
            "pain_points": [
                "Your Squarespace site looks decent on desktop but scores 50 on mobile PageSpeed. Half your traffic comes from phones. Half your potential patients leave before the page loads.",
                "You rank on page 3 for your top treatment terms. The med spas on page 1 have more pages, better schema markup, and faster sites.",
                "Your agency charges $2,000 to $4,000 per month for SEO but produces 2 blog posts and a monthly report. Your rankings have not moved in 6 months.",
            ],
            "workflow": [
                "We audit your site: PageSpeed scores, local SEO gaps, treatment page coverage, schema markup, and Google Business Profile alignment.",
                "We build a fast, premium site: treatment pages, provider bios, before/after galleries, location details, and booking integration.",
                "Local SEO: treatment-specific pages targeting '[treatment] + [city]' keywords. Medical practice schema markup.",
                "For events (grand openings, treatment showcases), we build registration pages with local ad targeting.",
                "Facebook and Instagram ads target local audiences within your service radius.",
                "Monthly SEO management available: content expansion, review management, and local ranking monitoring.",
            ],
            "pricing_context": f"Website build: ${PRICING['site_standard']['low']:,} to ${PRICING['site_standard']['high']:,}. SEO buildout: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Monthly SEO: ${PRICING['seo_monthly']['low']:,} to ${PRICING['seo_monthly']['high']:,}/mo. Event sites: ${PRICING['event_first']['low']:,} to ${PRICING['event_first']['high']:,}.",
            "faqs": [
                {"question": "Can you include before/after galleries?", "answer": "On the website, yes. For Facebook/Instagram ads, Meta restricts before/after patient imagery. We use lifestyle and treatment imagery for ads, while your site can display whatever your practice is comfortable showing."},
                {"question": "Do you integrate with booking systems?", "answer": "We can embed or link to your booking platform (Jane App, Vagaro, Boulevard, etc.). The site drives traffic; your booking system handles scheduling."},
                {"question": "How do you handle local SEO for med spas?", "answer": "Treatment-specific pages targeting '[treatment] + [city]' keywords, local business schema, Google Business Profile optimization, and location-specific content."},
                {"question": "What if I already have a site I like the look of?", "answer": "We can replicate your design on a static stack. Same look, 90+ PageSpeed score, no CMS maintenance."},
            ],
            "deep_dive": [
                "Med spa marketing is visual, local, and trust-dependent. Potential patients are deciding whether to inject a substance into their face. They search Google, evaluate your site in seconds, and form an impression of your practice before they walk through the door. A slow site with stock photos undermines the premium positioning your practice depends on.",
                "Local SEO is where the budget works hardest. A med spa in Scottsdale competes for 'Botox Scottsdale,' 'lip filler Scottsdale,' 'CoolSculpting Scottsdale,' and dozens of similar terms. A 10-page site competes for 3 of them. A 50-page site competes for all of them.",
                "Page speed compounds with conversion rate. Google research shows 53% of mobile visits are abandoned if a page takes longer than 3 seconds. Most Squarespace med spa sites take 3 to 5 seconds. A static site loads in under 1 second. The patients who would have bounced now see your treatment pages.",
                "Event marketing for med spas (grand openings, treatment showcases) follows a specific pattern. Local targeting within a 10 to 15 mile radius, interest-based audiences for aesthetics and skincare, and registration pages that preview the experience with specific treatments and promotional offers.",
            ],
            "outbound_links": [
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
                {"text": "Google Business Profile", "url": "https://www.google.com/business/"},
            ],
        },
        {
            "slug": "real-estate",
            "name": "Real Estate",
            "title": "Web Design and SEO for Real Estate Companies",
            "description": "Fast websites and SEO for real estate. Property launch pages, local SEO, investor event sites, and ad campaigns. Flat fees, 90+ PageSpeed.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Real Estate</span>',
            "intro": "Property launches, investor presentations, brokerage websites. Most brokerage sites are MLS-integrated WordPress builds that score 45 on mobile PageSpeed. Buyers searching on their phones leave before listings render.",
            "pain_points": [
                "Your brokerage site is built for listings, not marketing. When you need a page for a property launch or investor event, the options are a PDF flyer or a generic form.",
                "Your site loads in 5 seconds on mobile. Buyers tap the back button before your listings render.",
                "Facebook ads for real estate require Special Ad Category compliance. Most agencies do not know how to work within those targeting restrictions.",
            ],
            "workflow": [
                "We audit your current site: PageSpeed, SEO, content gaps, and conversion opportunities.",
                "We build a fast brokerage or property site: listing pages, market area content, agent bios, and lead capture.",
                "For property launches, we build premium registration pages with tracking and targeted ad campaigns.",
                "Local SEO: neighborhood pages, market area content, property type pages.",
                "Ad campaigns run within Meta Special Ad Category constraints with custom audiences.",
                "Template cloning for multi-property firms: consistent branding, separate tracking per project.",
            ],
            "pricing_context": f"Website build: ${PRICING['site_standard']['low']:,} to ${PRICING['site_content']['high']:,}. Event/launch pages: ${PRICING['event_first']['low']:,} to ${PRICING['event_first']['high']:,}. Ad management: ${PRICING['ad_monthly']['low']:,} to ${PRICING['ad_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "Can you include property renderings and floor plans?", "answer": "Yes. High-resolution images, renderings, floor plan PDFs, and embedded maps on the page."},
                {"question": "How do Special Ad Category restrictions affect targeting?", "answer": "Meta disables age, gender, and zip code targeting for housing ads. We compensate with interest-based targeting, custom audiences, and lookalike audiences."},
                {"question": "Can you build MLS-integrated sites?", "answer": "We build the marketing and content layer. For live MLS integration, we recommend pairing with an IDX provider. Static pages load fast; MLS search runs as a separate component."},
                {"question": "Do you handle multi-property portfolios?", "answer": "Yes. Each property gets its own branded site with separate tracking. The template model keeps design consistent."},
            ],
            "deep_dive": [
                "Real estate websites face a unique performance challenge. MLS-integrated sites pull listing data from external APIs, adding load time. IDX plugins on WordPress compound the problem. The result: most brokerage sites score 30 to 50 on mobile PageSpeed.",
                "The solution: separate the marketing layer from the listing layer. Static pages for neighborhood content, market reports, and agent bios load in under a second. The MLS search runs separately. Buyers find your site through local search (fast content pages rank), then use listing search once on site.",
                "Property launch pages serve double duty: registration tool and marketing asset. High-resolution renderings, floor plans, pricing context, and developer credentials all belong on the page. A PDF flyer does not cut it for a $50 million development.",
                "Local SEO for real estate targets specific neighborhoods and property types. Pages like 'condos in downtown Austin' capture search traffic from buyers evaluating locations. Each page is a landing pad for a specific intent, built at scale with programmatic SEO.",
            ],
            "outbound_links": [
                {"text": "Meta Special Ad Categories", "url": "https://www.facebook.com/business/help/298000447747885"},
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
            ],
        },
        {
            "slug": "healthcare-practices",
            "name": "Healthcare Practices",
            "title": "Web Design and SEO for Healthcare Practices",
            "description": "Fast websites and local SEO for clinics, dental practices, and specialty providers. 90+ PageSpeed, patient acquisition, flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Healthcare Practices</span>',
            "intro": "Clinics, dental practices, orthopedic groups, dermatology offices. Your patients search Google before they call. If your site loads slowly, ranks poorly, or looks dated, they book with the practice that shows up first.",
            "pain_points": [
                "Your WordPress site was built 4 years ago. It scores 45 on mobile PageSpeed, the plugins need updating, and the design looks like every other practice in your market.",
                "You pay an agency $2,500/mo for SEO. They produce a monthly report and 2 blog posts. Your rankings have not moved.",
                "Patients search '[specialty] near me' on their phones. Your competitors with faster sites and more content show up first.",
            ],
            "workflow": [
                "We audit your site: PageSpeed, local SEO, service page coverage, schema markup, and Google Business Profile.",
                "We build a fast practice site: service pages, provider bios, location details, patient resources, and booking integration.",
                "Local SEO: service-specific pages targeting '[treatment] + [city]' keywords. Medical practice schema markup.",
                "Content expansion: condition pages, treatment guides, FAQ pages targeting patient search queries.",
                "Optional: patient acquisition ads on Facebook/Instagram with local targeting.",
                "You own all files. No CMS maintenance, no hosting fees, no plugin updates.",
            ],
            "pricing_context": f"Practice website: ${PRICING['site_standard']['low']:,} to ${PRICING['site_standard']['high']:,}. SEO buildout: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Monthly SEO: ${PRICING['seo_monthly']['low']:,} to ${PRICING['seo_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "Can you integrate with our patient portal?", "answer": "We link to your patient portal and booking system. The website drives traffic; your existing systems handle scheduling and records."},
                {"question": "Do you handle HIPAA considerations?", "answer": "Our sites do not collect protected health information. Contact forms capture name, email, and message. For appointment requests, we link to your HIPAA-compliant booking system."},
                {"question": "How many pages does a typical practice site need?", "answer": "10 to 25 pages: homepage, about, providers, 8-15 service pages, location, contact, and patient resources. For SEO expansion, we add condition and treatment guide pages."},
                {"question": "Can you migrate our existing WordPress site?", "answer": "Yes. Same design or improved, 5x faster load times, no ongoing maintenance."},
            ],
            "deep_dive": [
                "Healthcare practices face intense local competition online. The practices on page 1 have fast sites, more content, and proper local SEO markup. Page speed is the easiest to fix and has the most immediate impact.",
                "Service pages are the backbone of practice SEO. Each service should have its own page targeting '[service] + [city]' keywords. Ten service pages compete for 10 keyword clusters. Three generic pages compete for none.",
                "Patient search behavior is specific. They search 'best orthopedic surgeon in Scottsdale' or 'Invisalign cost Denver.' Each query is an opportunity for a page that answers that exact question. Programmatic SEO scales this approach.",
                "Google Business Profile alignment matters. Your website, GBP listing, and schema markup should tell a consistent story. Inconsistencies weaken local rankings.",
            ],
            "outbound_links": [
                {"text": "Google Business Profile", "url": "https://www.google.com/business/"},
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
            ],
        },
        {
            "slug": "law-firms",
            "name": "Law Firms",
            "title": "Web Design and SEO for Law Firms",
            "description": "Fast websites and SEO for law firms. Practice area pages, attorney bios, local SEO, lead generation. 90+ PageSpeed scores, flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Law Firms</span>',
            "intro": "Law firm marketing is SEO-dependent. Your next client is searching Google right now. If your site ranks, they call you. Most law firm sites are bloated WordPress builds that score 50 on mobile, with 3 practice area pages competing against firms with 50.",
            "pain_points": [
                "You pay a legal marketing agency $3,000 to $5,000 per month. They produce 4 blog posts and a report. Your rankings have not improved.",
                "Your WordPress site has 15 plugins, takes 4 seconds to load, and needs a security update every month.",
                "Competitor firms with faster sites and more content pages are outranking you for the exact terms your clients search.",
            ],
            "workflow": [
                "We audit your site: PageSpeed, keyword rankings, practice area coverage, schema markup, and local SEO.",
                "We build a fast, professional site: practice area pages, attorney bios, case results, testimonials, and lead capture.",
                "SEO buildout: practice area pages, FAQ pages, and location pages for multi-office firms.",
                "Schema markup: Attorney, LegalService, and LocalBusiness schema on every relevant page.",
                "Optional: Google Ads or Facebook campaigns for lead generation with full conversion tracking.",
                "You own all files. No CMS maintenance, no agency lock-in.",
            ],
            "pricing_context": f"Law firm website: ${PRICING['site_standard']['low']:,} to ${PRICING['site_content']['high']:,}. SEO buildout: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Monthly SEO: ${PRICING['seo_monthly']['low']:,} to ${PRICING['seo_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "Do you work with specific practice areas?", "answer": "We work across practice areas: personal injury, family law, criminal defense, estate planning, business law, immigration. The SEO principles are the same; the content and keywords are practice-specific."},
                {"question": "Can you include case results and testimonials?", "answer": "Yes, with appropriate disclaimers per your state bar rules."},
                {"question": "How do you handle multi-office firms?", "answer": "Each office gets a location page with its own address, phone, and local schema. Practice area pages can target multiple locations."},
                {"question": "What about attorney directory sites?", "answer": "Your own site should be the primary destination. Directory profiles supplement your presence but should link back to your site."},
            ],
            "deep_dive": [
                "Law firm SEO is one of the most competitive local search categories. The firms on page 1 invested in content volume, site speed, and local SEO signals. A 15-page site cannot compete with a 100-page site targeting every practice area, sub-practice, and location combination.",
                "Practice area pages are the most important content type. 'Personal injury lawyer Phoenix' is different from 'car accident attorney Phoenix.' Each query represents a different potential client. Each deserves its own page.",
                "Page speed matters for lead generation. A potential client who just had a car accident searches on their phone. If your page takes 4 seconds, they hit back and click the next result. Static HTML loads in under a second.",
                "Legal marketing agencies charge $3,000 to $8,000/mo for a handful of blog posts. Programmatic SEO generates practice area, FAQ, and location pages at scale. The build happens once; the SEO compounds.",
            ],
            "outbound_links": [
                {"text": "Google Search Console", "url": "https://search.google.com/search-console/about"},
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
            ],
        },
        {
            "slug": "home-services",
            "name": "Home Services",
            "title": "Web Design and SEO for Home Service Companies",
            "description": "Fast websites and local SEO for HVAC, plumbing, roofing, and home service companies. 90+ PageSpeed, flat fees, local search rankings.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Home Services</span>',
            "intro": "HVAC, plumbing, roofing, electrical, landscaping. Your customers search Google when something breaks. If your site ranks for 'AC repair [city],' you get the call. Local SEO is everything in home services.",
            "pain_points": [
                "You pay a marketing agency $2,000 to $5,000/mo for SEO. They built your site 3 years ago and send a monthly report. Rankings have barely moved.",
                "Your site scores 40 on mobile PageSpeed. Homeowners with a burst pipe are not waiting 5 seconds for your page to load.",
                "You serve 15 cities but have one location page. Your competitor has a page for each city and ranks in all of them.",
            ],
            "workflow": [
                "We audit your site: PageSpeed, local keyword rankings, service area coverage, and Google Business Profile.",
                "We build a fast site: service pages, service area pages, reviews/testimonials, and lead capture (phone + form).",
                "Local SEO: service-specific pages for each city. 'AC repair Scottsdale,' 'AC repair Mesa,' each as a unique page.",
                "Schema markup for local business, service area, and service types.",
                "Optional: Google Ads or Facebook campaigns for emergency and seasonal services.",
                "You own the site. No CMS, no hosting fees, no monthly lock-in unless you want ongoing SEO.",
            ],
            "pricing_context": f"Website build: ${PRICING['site_standard']['low']:,} to ${PRICING['site_standard']['high']:,}. SEO buildout: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Monthly SEO: ${PRICING['seo_monthly']['low']:,} to ${PRICING['seo_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "How many service area pages do I need?", "answer": "One per city per major service. 10 services across 10 cities = 100 pages. Each targets a specific '[service] + [city]' keyword."},
                {"question": "Can you include online booking?", "answer": "We link to your scheduling system (Housecall Pro, ServiceTitan, Jobber). The website drives calls and form submissions."},
                {"question": "Do you help with Google Business Profile?", "answer": "We ensure your site content, NAP, and schema markup align with your GBP listing. Consistent signals strengthen local rankings."},
                {"question": "What about review management?", "answer": "We display your best reviews with schema markup. For active review management, we recommend pairing with a review platform."},
            ],
            "deep_dive": [
                "Home service SEO is hyperlocal. A plumber in Phoenix needs to rank in Phoenix, Scottsdale, Tempe, Mesa, and every city in their service area. Individual pages for each city with unique content rank. A single 'service areas' page listing 15 cities ranks for none.",
                "Emergency searches are the highest-intent queries. Someone searching 'emergency plumber near me' at 11 PM needs help now. If your page takes 4 seconds, they call the next result. A static site loads in under a second.",
                "Service pages are the foundation. Separate pages for each service with city targeting. Describe the service, explain the process, list service areas, show reviews, make the phone number prominent.",
                "Programmatic SEO generates service area pages at scale: 10 services across 15 cities = 150 pages, each targeting a specific local search term. The build happens once; rankings compound.",
            ],
            "outbound_links": [
                {"text": "Google Business Profile", "url": "https://www.google.com/business/"},
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
            ],
        },
        {
            "slug": "professional-services",
            "name": "Professional Services",
            "title": "Web Design and SEO for Professional Services Firms",
            "description": "Fast websites and SEO for accounting firms, consultancies, and financial advisors. 90+ PageSpeed, credibility sites that rank and convert. Flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Professional Services</span>',
            "intro": "Accounting firms, consultancies, financial advisors, insurance brokers. Your website is a credibility check. Every prospect visits your site before taking a meeting. If it looks like a 2018 Squarespace template with 5 pages, they are forming impressions before you speak.",
            "pain_points": [
                "Your Squarespace site has 5 pages, scores 55 on mobile, and the blog has not been updated in years.",
                "You rank nowhere for '[service] + [city].' Competitors with 30+ content pages are outranking you.",
                "Your competitors hired an agency at $150/hr. You need the same credibility at a fraction of the cost.",
            ],
            "workflow": [
                "We audit your site: PageSpeed, keyword gaps, service page coverage, and competitor benchmarking.",
                "We build a professional site: service pages, team bios, industry expertise pages, client results, and lead capture.",
                "SEO buildout: service-specific pages, industry vertical pages, and location pages for multi-office firms.",
                "Content architecture: blog infrastructure, resource pages, and FAQ pages.",
                "Schema markup for professional service, organization, and local business.",
                "You own all files. No CMS, no recurring platform costs.",
            ],
            "pricing_context": f"Professional services site: ${PRICING['site_standard']['low']:,} to ${PRICING['site_content']['high']:,}. SEO buildout: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Monthly SEO: ${PRICING['seo_monthly']['low']:,} to ${PRICING['seo_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "Can you match high-end agency sites?", "answer": "Yes. Clean, professional design with fast load times. Static HTML at a flat fee instead of WordPress at $150/hr."},
                {"question": "How do you handle multi-office firms?", "answer": "Each office gets a location page with local schema. Service pages can target multiple locations."},
                {"question": "What about client testimonials?", "answer": "Dedicated sections for client results and testimonials. For regulated industries, we include required disclaimers."},
                {"question": "Do you build thought leadership content?", "answer": "We build blog infrastructure, Article schema, and content architecture. You provide expertise; we package it for search."},
            ],
            "deep_dive": [
                "Professional services firms win on credibility. Your website is the first thing a prospect checks after a referral. A fast, well-designed site with content depth signals competence and investment in your practice.",
                "Service and industry vertical pages are the SEO foundation. A CPA firm serving restaurants, real estate investors, and startups should have separate pages for each. Each targets specific search queries and demonstrates specialized expertise.",
                "Most professional services firms underinvest in web presence. Meanwhile, competitors with better sites capture prospects who search before asking for referrals. The firm that ranks first for 'business attorney Denver' gets the call.",
                "Page speed signals professionalism. A consulting firm advising on operational efficiency should not have a 4-second load time. A sub-1-second site demonstrates the attention to detail clients expect.",
            ],
            "outbound_links": [
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
                {"text": "Google Search Console", "url": "https://search.google.com/search-console/about"},
            ],
        },
        {
            "slug": "startups",
            "name": "Startups & Early-Stage SaaS",
            "title": "Web Design and SEO for Startups",
            "description": "Fast marketing sites and SEO for startups on a bootstrap budget. 90+ PageSpeed, programmatic SEO, no agency overhead. Ship in weeks.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Startups</span>',
            "intro": "You are building a product with a lean team and a bootstrap budget. Your marketing site should not cost $15,000 or take 8 weeks. It should load fast, rank well, and convert visitors into signups. Ship it in weeks, not months.",
            "pain_points": [
                "You built your landing page on Webflow because it was fast to launch. Now it scores 68 on mobile PageSpeed, costs $30/mo to host, and you cannot customize schema markup.",
                "You have 5 marketing pages competing against incumbents with 200+. Content velocity matters for SEO and you cannot hire a content team yet.",
                "Agencies want $10,000 to $20,000 and 6 weeks. You need that budget for product development.",
            ],
            "workflow": [
                "We scope the minimum viable marketing site: homepage, product/features, pricing, about, and CTA.",
                "We build it static: 90+ PageSpeed, full schema, mobile-first. Deployed for $0 hosting on Netlify or GitHub Pages.",
                "If you need SEO, we build programmatic pages: comparison pages, use case pages, integration pages.",
                "Lead capture via Formspree, your CRM, or a custom webhook.",
                "You own all files. Fork the repo, deploy anywhere.",
                "When ready to scale, we expand content and build SEO infrastructure.",
            ],
            "pricing_context": f"Landing page: ${PRICING['site_landing']['low']:,} to ${PRICING['site_landing']['high']:,}. Standard site: ${PRICING['site_standard']['low']:,} to ${PRICING['site_standard']['high']:,}. Programmatic SEO: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}.",
            "faqs": [
                {"question": "Can you ship a site in under 2 weeks?", "answer": "Landing pages: 1 to 2 weeks. Standard 5-page sites: 2 to 3 weeks. The constraint is usually content, not build time."},
                {"question": "Is this cheaper than Webflow?", "answer": "Upfront cost is similar. Ongoing cost is $0 (Webflow charges $14 to $39/mo). Over 2 years, the static site saves $300 to $1,000 in hosting plus you get a 90+ PageSpeed score."},
                {"question": "Can I edit the site myself?", "answer": "You own the HTML/CSS/JS files. If your team can edit HTML, you can make changes directly."},
                {"question": "What about analytics and A/B testing?", "answer": "GA4 is included. For A/B testing, we can integrate with PostHog, Splitbee, or similar tools."},
            ],
            "deep_dive": [
                "Startups waste money on marketing sites. An agency charges $15,000 for a WordPress site that scores 65 on PageSpeed. A Webflow template locks you into monthly fees. A static site costs $3,000 to $6,000, deploys for free, scores 90+, and you own every file.",
                "SEO for startups should be programmatic from day one. Your incumbents have hundreds of pages. Programmatic SEO generates comparison, alternative, and use case pages at scale. Twenty pages on day one beats 2 per month for a year.",
                "Speed matters disproportionately for startups. You are unknown. Every visitor evaluates you for the first time. A slow site creates doubt. A fast site communicates competence.",
                "The ownership model matters. If your site lives on Webflow and your marketing lead leaves, it is locked in their account. Git repository = any developer can modify and deploy it.",
            ],
            "outbound_links": [
                {"text": "Cloudflare Pages", "url": "https://pages.cloudflare.com/"},
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
            ],
        },
        {
            "slug": "franchise-multi-location",
            "name": "Franchise & Multi-Location",
            "title": "Web Design and SEO for Franchise and Multi-Location Businesses",
            "description": "Consistent websites and local SEO for franchise and multi-location businesses. Template cloning, per-location tracking. Flat fees.",
            "h1": 'Web Design &amp; SEO for <span class="text-accent">Franchise &amp; Multi-Location</span>',
            "intro": "Franchises need consistent branding across every market with local SEO for each location. Most franchise websites are a single corporate site (no local SEO) or a collection of inconsistent location pages (no brand consistency). The template cloning model solves both.",
            "pain_points": [
                "Your corporate site has one 'locations' page listing 25 addresses. None of those locations rank individually for local search.",
                "Each franchisee built their own site. Designs are inconsistent, branding drifts, and nobody knows which sites have tracking.",
                "Your agency charges per location for SEO. At $1,500/mo across 25 markets, the annual spend is $450,000. Rankings do not justify the cost.",
            ],
            "workflow": [
                "We build a master template: homepage, services, about, and location page structure with your brand guidelines.",
                "We clone the template for each location with local details: address, phone, hours, team bios, service area content.",
                "Each location gets local schema markup, unique meta titles/descriptions, and location-specific content.",
                "Separate tracking per location. Corporate dashboard for aggregate reporting.",
                "Local SEO: service-specific pages targeting '[service] + [city]' for each location.",
                "New locations clone from the template in 48 hours.",
            ],
            "pricing_context": f"Master template: ${PRICING['site_standard']['low']:,} to ${PRICING['site_content']['high']:,}. Per-location clone: ${PRICING['event_clone']['low']:,} to ${PRICING['event_clone']['high']:,}. SEO per market: ${PRICING['seo_programmatic']['low']:,} to ${PRICING['seo_programmatic']['high']:,}. Monthly SEO: ${PRICING['seo_monthly']['low']:,} to ${PRICING['seo_monthly']['high']:,}/mo.",
            "faqs": [
                {"question": "Can each location have unique content?", "answer": "Yes. The template provides consistent structure. Each location gets unique team bios, service area content, reviews, and local details."},
                {"question": "How do you handle 25+ locations?", "answer": "Programmatic generation. Build the template once, generate location pages from a data file. Adding a location = adding a row and rebuilding."},
                {"question": "Can franchisees make local changes?", "answer": "The data file approach lets franchisees update local details through a simple interface. Design is controlled centrally."},
                {"question": "What about brand compliance?", "answer": "The master template enforces brand guidelines. Individual locations customize content within the approved structure."},
            ],
            "deep_dive": [
                "Franchise SEO fails two ways. A single corporate site with one locations page: Google treats it as one site, individual locations do not rank. Or 25 independently built sites: inconsistent quality, fragmented brand. The template model splits the difference.",
                "One master template enforces brand consistency. Each location gets unique local content: team bios, service area descriptions, local reviews, address-specific schema. Google sees 25 locally relevant pages, not one generic corporate site.",
                "Programmatic generation makes multi-location SEO economical. Instead of $1,500/mo per location, the build script generates all location pages from structured data. 25 locations with 10 service pages = 250 pages in a single build.",
                "Tracking per location matters for franchise performance measurement. Each location gets its own analytics. Corporate sees aggregate traffic. Franchisees see their own performance. Ad campaigns target each market separately.",
            ],
            "outbound_links": [
                {"text": "Google Business Profile", "url": "https://www.google.com/business/"},
                {"text": "PageSpeed Insights", "url": "https://pagespeed.web.dev/"},
            ],
        },
    ]
